### ISSUE TITLE
Preferences should allow customization of file patterns to ignore

### ISSUE THREAD

**Issue by topfunky** [topfunky/PeepOpen-Issues#1]
PeepOpen currently uses a hard-coded list of files and directories to ignore. These should be configurable by the user.

**Comment by jacquescrocker** [comment]
It should also read the existing textmate ignore configuration. I have Textmate set to ignore a bunch of file paths, but its still showing up in PeepOpen

Also PeepOpen should look at Textmate's "treat as binary" so textmate doesnt show those. However they also appear in PeepOpen

**Comment by tibra** [comment]
For example:
When I have an automatic generated doc, lets say via rake doc:app, PeepOpen will match those entries from doc/app/classes/_/_\* sometimes before my actual file. I have to navigate down with keys to avoid skipping into auto generated docs.

A possibility like a dot ignore project file to turn of specific directories in a project would be nice.

**Comment by sentientmonkey** [comment]
+1 for this feature.  I have the same problem as tibra for a really big rails project, which bumps the number of files over the 4k limit.

Also, if it read/used a .gitignore as a default, that would also be awesome.

**Comment by akaHeimdall** [comment]
I take it this will allow for searching of the public directory and it's sub folders. Thanks much (I need to search my javascript files.)

**Comment by topfunky** [comment]
The upcoming v0.2.1 has an Advanced preference pane for entering a Regex of files and directories to ignore. A future update will have a nicer looking Predicate editor.
