### ISSUE TITLE
PeepOpen flakes out in Cocoa Emacs 23 and opens file in a new window

### ISSUE THREAD

**Issue by mwilliams** [topfunky/PeepOpen-Issues#10]
I had to comment out any lines that dealt with Carbon and Aquamacs key bindings for it to load correctly and I then had to launch it manually with M-x...  I could have re-bound the key in Textmate.el which I've been using for a long time now.

I would also expect the selected file to get opened in the current window and just create a buffer versus opening a new window entirely.  

So it works great and looks beautiful; but those were just a few bumps I hit along the way and I really need this to open up in current buffer (as I work full screen and don't want to deal with multiple Emacs windows).

Was this tested against the Cocoa build at all or just the old Carbon build and Aquamacs?

Thanks!

**Comment by topfunky** [comment]
I'm using it with Carbon Emacs, built in 2010 ( http://homepage.mac.com/zenitani/emacs-e.html ). 

I also run full screen, so it's important for me to get this right. I've heard a few reports about Emacs 23 and Aquamacs and hope to iron out all the issues soon.

I also have an updated peepopen.el from Josh Peek that should solve some of the keybinding problems. http://gist.github.com/364915

**Comment by mwilliams** [comment]
Im using the build here for fullscreen Emacs with the Cocoa build. Works like a charm!

http://www.emacswiki.org/emacs/EmacsForMacOS#toc24

I'm hoping the patch gets in the official build at some point. But it's definitely the way to go with Emacs!  I can do some testing with Josh's new peepopen.el and see what i  can come up with. Getting it to open in the existing window would be great. Also being able to use peep open for buffer listings and symbol jumping would be nice too. Great work, hope to get my $9 worth :)

**Comment by josh** [comment]
Try:

```
;; always open in the same window
(setq ns-pop-up-frames nil)
```

**Comment by mwilliams** [comment]
Thanks Josh, that takes care of that issue.  I'm still unable to open the dialog with command-t with your gist, it's opening the font dialog box...  quirky.  I'm using the ELPA install of Textmate.el (and have been for a while) but I don't think there's much of a difference).  I'll still hack away at it...  Otherwise, getting closer.  Thanks for the help.  

Adding Josh's snippet above might be good to add to the README as well.  I would imagine that should be the default behavior....

**Comment by josh** [comment]
Give my peepopen.el fork a try: http://github.com/josh/emacs/blob/master/elpa-to-submit/peepopen.el

topfunky said he plans to integrate my changes in the next release.

**Comment by aurelienbottazini** [comment]
Hello,
I tried to add the ns-pop-up-frames josh suggested but it still opens the file in a new window (and this new window crash when I switch focus to it).

I tried with emacs compiled from here: http://www.stratospark.com/blog/2010/fullscreen_emacs_on_osx.html
and here http://emacsformacosx.com/

I will try to investigate further

**Comment by fullofcaffeine** [comment]
I had to set the shortcut using global-set-key, like this:

(global-set-key (kbd "s-t") 'peepopen-goto-file-gui)

The other code was somehow setting the shortcut to call the font settings dialog. If anyone knows why, I'd like to know ;)

Marcelo.

**Comment by thillerson** [comment]
I also broke down and used a global keybinding - C-x C-o which I like better anyway. 

In any case, I install cocoa emacs through homebrew (`brew install emacs --cocoa`) and I'm getting the open in a new window problem too. +1

**Comment by thillerson** [comment]
I didn't read deep enough into the comments. This gist works for me: http://gist.github.com/391838

**Comment by topfunky** [comment]
Seems that the ns-pop-up-frames is working for most. I'm closing this ticket. (Also added it to the built-in help.)

```
(setq ns-pop-up-frames nil)
```

**Comment by magnars** [comment]
I still have this problem with a `brew install emacs --cocoa` v23.3. It is not a matter of pop-up-frames, because PeepOpen actually launches an entirely new Emacs instance. Opening a file with Emacs using Alfred works properly.
