### ISSUE TITLE
Peepopen triggers a switch to dedicated graphics on new MBP

### ISSUE THREAD

**Issue by DylanFM** [topfunky/PeepOpen-Issues#102]
http://skitch.com/dylanfm/dkebg

A very minor issue, but Peepopen causes the dedicated graphics to be activated on the latest Macbook Pros. It's a little bit of a bummer when working on battery power. [This little menu bar app](http://codykrieger.com/gfxCardStatus/) (see screenshot above) allows you to force integrated graphics, but for those who don't have something like this installed, they're going to get worse battery life. I'm not sure why it's triggered, but it could have something to do with certain libraries being called.

**Comment by topfunky** [comment]
You can turn off PeepOpen's graphic card usage. Go to PeepOpen's Preferences, Advanced Pane, and uncheck "Use Core Animation." Restart PeepOpen and it won't use the Nvidia graphics card.
