### ISSUE TITLE
file ordering less effective than Go To File

### ISSUE THREAD

**Issue by jjb** [topfunky/PeepOpen-Issues#103]
Similar to #92

Here I'm searching for the **cont**ents **con**troller **test**. PeepOpen lists it second:

![PeepOpen](http://img.skitch.com/20100629-ceh1gfj7ygh7wfdax2yekxgx6j.png)

Go to File lists it first, and I like its second choice as well:

![PeepOpen](http://img.skitch.com/20100629-rctt67ip9mexfx3grnwip3re9b.png)

Notice how Go to File associates (highlights in bold) the second T with "test" instead of "controller", even though the T in controller comes first in the file name. It must be giving priority to first letters after underscores, or some other heuristics that parses the path into "words". (a la my suggestion in #83 :) )

As always, thanks for listening.

John

**Comment by topfunky** [comment]
Version 0.2.2 (just released) prioritizes early matches over long matches, which fixes the previous undesired behavior. Try it out!

**Comment by jjb** [comment]
much better, awesome
