### ISSUE TITLE
PeepOpen can't find macport git executable

### ISSUE THREAD

**Issue by newzealandpaul** [topfunky/PeepOpen-Issues#105]
I am running Mac OS 10.6.4, MacPorts 1.8.2 and git 1.7.1 (installed
via. macports).

Git is installed in the standard macports location ...

$ which git
/opt/local/bin/git

PeepOpen is not able to locate the git executable. It says "Git not found".

**Comment by ghost** [comment]
same problem here; though my `git` executable is in `~/.opt/local/bin`. as a work around i symlinked the git executable into `/usr/bin`.

**Comment by kennethreitz** [comment]
+1

**Comment by stjernstrom** [comment]
+1

**Comment by kennethreitz** [comment]
if you set a symlink from your git executable to `/usr/bin/git`, the problem is fixed.

**Comment by stjernstrom** [comment]
Symlink git to /usr/bin/git makes my PeepOpen happy
  sudo ln -s /opt/local/bin/git /usr/bin/git

**Comment by newzealandpaul** [comment]
I believe the latest update (0.2.3) fixes this problem.

**Comment by kennethreitz** [comment]
@paulwilliam: what?

**Comment by newzealandpaul** [comment]
@kennethreitz errr ... yea ... I have edited my previous comment so it makes sense
