### ISSUE TITLE
In Textmate, PeepOpen doesn't respond when the cursor is in the bottom text search bar

### ISSUE THREAD

**Issue by whatbird** [topfunky/PeepOpen-Issues#108]
in TextMate when searching (ctrl+s), if the cursor is at the bottom there, the default TM file switcher shows up instead of PeepOpen.

sorry if dupe, thanks,
-c

**Comment by topfunky** [comment]
The newest TextMate plugin in PeepOpen 0.3.0 should fix this issue. Give it a shot with the "Check for Updates" menu item.
