### ISSUE TITLE
Support for mouse clicks

### ISSUE THREAD

**Issue by chrisb** [topfunky/PeepOpen-Issues#109]
Sometimes I use my mousewheel to scroll down the list and find myself clicking an entry to open it, which doesn't do anything.

Issues:
1. On clicking a file the entry turns to a weird blue selected state. Pressing return now does not function. In order to actually open the file I need to focus the text field and then press return.
2. Clicking an entry should function the same way as pressing return.

**Comment by topfunky** [comment]
0.3.1 now supports mouse clicks on the table cells.
