### ISSUE TITLE
TextMate doesn't use PeepOpen with no open documents in a project

### ISSUE THREAD

**Issue by veganstraightedge** [topfunky/PeepOpen-Issues#11]
Opened a Rails app as a project in TextMate with "mate ."
Before opening any files, pressed CMD-T.
TextMate opened its built in file opener thingy.
Used it to open any file.
With that file still open, CMD-T again.
TextMate uses PeepOpen.

**Comment by jacquescrocker** [comment]
Seeing the same issue. I think its a textmate issue. Sort of a bummer because this is the most often place where I need to open a file (right after opening a new textmate project)

**Comment by topfunky** [comment]
Unfortunately, TextMate doesn't activate bundle commands until a file is open. I'm considering implementing part of PeepOpen as a native TextMate plugin, which could solve the problem. However, that might be a few weeks out.

**Comment by noctivityinc** [comment]
Native TM plugin as in not a separately running app?  That would rock the house!  Thanks for the great work.

**Comment by sacrosby** [comment]
Yea, still getting this problem. Took me a while to notice where it was popping up, but it's a pain. I frequently close all my open documents and use command-T. If I'm not mistaken, when I bought the app (on day 3 or something?) it didn't do this? I could be wrong.

**Comment by pietern** [comment]
I've created a TextMate plugin that does exactly this. You can find the code and binary version at [the repo](http://github.com/pietern/PeepOpen-tmplugin). It's the most simple plugin I've ever seen, but does its job :-)

**Comment by topfunky** [comment]
A compiled version of @pietern's plugin is here (and fixes the "no files open" issue):

```
http://github.com/topfunky/PeepOpen-EditorSupport/downloads
```

Download and install PeepOpen.tmplugin into ~/Library/Application Support/TextMate/Plugins. It will be the default in future releases of PeepOpen.

Thanks @pietern!
