### ISSUE TITLE
Textmate: Need to reload manually?

### ISSUE THREAD

**Issue by MarioRicalde** [topfunky/PeepOpen-Issues#111]
I have a project; when I create, rename, or delete any file. The changes are not reflected on Peepopen. I need to hit ⌘ R ALWAYS?

**Comment by opsb** [comment]
This one caught me out, I definitely expect reindexing to be automatic when files are created/renamed/deleted.

**Comment by topfunky** [comment]
We're experimenting with watching the filesystem for events. In the meantime, we've made refresh more reliable so it should be a quick operation. It will also save your search so you can do it mid-search.
