### ISSUE TITLE
Feature Request: Allow to Modify Files within PeepOpen

### ISSUE THREAD

**Issue by MarioRicalde** [topfunky/PeepOpen-Issues#112]
I would like to replace "projects bar" COMPLETELY since I feel it makes me waste time navigating through directories. I would love to be able to use FInder Hotkeys to modify files within PeepOpen, heck I would even pay for that feature.

This would also mean the user should be able to select folders by using the /path/to/folder/ 

For example:

⌘T
index (selects index.php)
⌘R ( Rename File )
Insert "some name"
window closes

⌘T
images/ ( displays all folders named images )
⌘R ( Rename Folder )
Insert "some name"
window closes

I'm willing to pay for this feature. But would love to see it included inside peepopen (even if it's a paid upgrade). This would make TextMate soo good.

**Comment by topfunky** [comment]
That's an interesting idea, but is completely different from what PeepOpen was built to do. It's not too hard to make a native plugin for TextMate. Maybe someone else can build this as a separate project?
