### ISSUE TITLE
PeepOpen crashes immediately (after initial install)

### ISSUE THREAD

**Issue by edruder** [topfunky/PeepOpen-Issues#114]
I purchased PeepOpen, immediately downloaded and ran it, eager to experience the topfunky PeepOpen goodness. Unfortunately, double-clicking the app didn't result in any visible effects (after the standard OS X icon zoom effect, that is)--no UI appeared, no icon in the menu bar. :(

Here's the only thing in the CrashReporter log file (one of which is created every time I double-click PeepOpen, so I have lots of 'em!):

```
Process:         PeepOpen [64173]
Path:            /Applications/PeepOpen.app/Contents/MacOS/PeepOpen
Identifier:      com.topfunky.PeepOpen
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [118]

Date/Time:       2010-07-22 13:26:17.118 -0700
OS Version:      Mac OS X 10.5.8 (9L30)
Report Version:  6
Anonymous UUID:  4EF441E4-4582-46C6-96F7-E053AF4678A8

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  unknown required load command 0x80000022
```

Any thoughts about how I can get around this problem and start using PeepOpen?

**Comment by edruder** [comment]
The crash above happened on a MacBook Pro with the latest OS X Leopard installed.

I just installed and ran PeepOpen on a different MacBook Pro with the latest OS X Snow Leopard installed, and had no problems--the PeepOpen UI started, the menu bar icon installed, all is well.

**Comment by edruder** [comment]
Darn--didn't mean to close this issue! (I wasn't thinking when I clicked Comment and Close--thought it would close the comment editor or something.)

I can't figure out how to reopen this issue, either!

**Comment by topfunky** [comment]
Unfortunately, PeepOpen is Snow Leopard only and won't work on 10.5.8.

We're glad to give you a refund. Email boss@topfunky.com (or upgrade to Snow Leopard and it will work).

**Comment by edruder** [comment]
Ah, I'll keep it for the one Mac I have that I've upgraded to Snow Leopard. I guess it'll never work on my workhorse PowerMac G5. :(

**Comment by dvdrtrgn** [comment]
I just ran into this, too. I didn't see the Snow Leopard Only disclaimer... No code that can check for this, instead of just crashing?

**Comment by topfunky** [comment]
We're now using MacRuby 0.9 which should solve some crashes under Mac OS X 10.6. Unfortunately, it still only works on Snow Leopard and we don't have a way to check for older versions before our code is executed.

Give PeepOpen 0.3.0 it a shot with the "Check for Updates" menu item.
