### ISSUE TITLE
Improve readability of file paths

### ISSUE THREAD

**Issue by opsb** [topfunky/PeepOpen-Issues#115]
Compared to the built-in textmate dialog I find it much harder to scan the filenames. Some thoughts I had on this:

1) I don't need an icon to indicate the file type, I automatically scan the end of the filename anyway. Given that the file extension if visible it seems like unnecessary duplication. Usually I know what extension I'm after anyway so I'd put that on the end of my search string.

2) I'd prefer the time to be on the same line as the filename. I'm not sure where the best position would be, perhaps right aligned in place of the icons.

**Comment by topfunky** [comment]
There's now an option to hide file icons. See Preferences > Editor > Show Filetype Icons

**Comment by opsb** [comment]
That's great, just switched the icons off. 

With regards to point 2, I don't think I've ever once looked at the time under the filename, when I have the dialog up I already know which file I'm looking for so the time is irrelevant. An option to hide it would be awesome :)

Thanks again.
