### ISSUE TITLE
Dmg installation doesn't Work - alternative installation instructions?

### ISSUE THREAD

**Issue by jackkinsella** [topfunky/PeepOpen-Issues#116]
Just downloaded PeepOpen yesterday and am very excited about getting started. Unfortunately I can't get it to start. I installed using the standard drag the app into the applications folder then double clicking the app. When I do this I see nothing. I'm using the latest version of Textmate.

Also running in cmd prompt with "open PeepOpen.app/" gives this error:

LSOpenFromURLSpec() failed with error -10810 for the file /Users/jack/Desktop/peepopen/PeepOpen.app.

If I try running "ruby rb_main.rb" I get 'uninitialized constant NSBundle (NameError)'. 

Did I miss something in the installation instructions?

Jack

**Comment by topfunky** [comment]
Try downloading it again. You may have received a partial copy.

PeepOpen works on Snow Leopard, 64-bit machines only.

**Comment by jackkinsella** [comment]
thanks -- I'm still running Leopard so that's the issue. Thought the blurb on the site meant it only worked in Emacs with 64 bit machine.

**Comment by johnpaulashenfelter** [comment]
I'm getting this exact error on a brand-new Macbook Pro (Sandybridge) running SL

**Comment by ghost** [comment]
+1 error on 2011 MBP.

**Comment by johnpaulashenfelter** [comment]
Any update?

**Comment by topfunky** [comment]
I haven't seen anything from the MacRuby team. I'm going to try to contact someone personally tomorrow and figure out a fix.
