### ISSUE TITLE
Support multiple editors simultaneously

### ISSUE THREAD

**Issue by shaug** [topfunky/PeepOpen-Issues#117]
I use Xcode for writing Objective-C code, and TextMate for everything else. I'd love it if PeepOpen could support both editors simultaneously. Rather than blindly opening the requested file in the configured editor, I'd prefer it if it could look at the invoking app and open the file in it if supported by PeepOpen.

**Comment by krogh** [comment]
Hi and thank you for this nice performance enhancer.
As  shaug said above it would be really neat if PeepOpen could support several editors simultaneously.

Best regards
Michael

**Comment by topfunky** [comment]
PeepOpen 0.3.0 and better now uses its own URL scheme. This means that it can be used by multiple editors at once.

Install the new plugins in 0.3.0 or look at the documentation for information on how to write a plugin that works with the new URL scheme.

We're working on Xcode 4 compatibility. It seems that the User Scripts have been removed, but there may be other ways to run PeepOpen within Xcode 4.
