### ISSUE TITLE
Selecting a file when using MacVim does not return focus to MacVim

### ISSUE THREAD

**Issue by spicycode** [topfunky/PeepOpen-Issues#12]
It generally opens the file in question, but it does not switch active app focus back to it. 

I'm on MacVim Snapshot 52 (the latest stable release is ancient, the snapshots are current).

**Comment by topfunky** [comment]
I've uncovered a related problem where if there is no file open in MacVim initially, the request to open a file from PeepOpen fails. Opening at least one file in MacVim solves the problem.

Sometimes, background MacVim processes intercept the request to open a file, and it never gets opened in the app.

However, it should be easier than that. I'm looking into better ways to solve this problem smoothly.

**Comment by spicycode** [comment]
I am as well, once I got the build setup I'm working on activating MacVim using the normal OSX workflow (which should be possible on the latest builds).

**Comment by topfunky** [comment]
This should be fixed since v0.2.0. PeepOpen uses "open -a MacVim" which should honor the running copy of MacVim.

See also the PeepOpen help for MacVim for other tips.
