### ISSUE TITLE
MacVim can't open in current window anymore?

### ISSUE THREAD

**Issue by tobi** [topfunky/PeepOpen-Issues#122]
It seems the open to open new files in current window isn't in MacVim anymore: 

http://skitch.com/tobiasluetke/dqh7w/general

Any idea on how to use PeepOpen now?

**Comment by b4winckler** [comment]
You can still set MacVim to open files in the current window in the "General Preferences".  Under "Open files from applications:" select "in the current window".

Please file MacVim bugs/requests/questions that have nothing to do with PeepOpen on the [vim_mac](http://groups.google.com/group/vim_mac) Google group.  Thanks!

**Comment by loe** [comment]
I don't have a "General Preferences"

edit: I see you mean in MacVim.
