### ISSUE TITLE
Can no longer change peepopen shortcut

### ISSUE THREAD

**Issue by scottillogical** [topfunky/PeepOpen-Issues#124]
I'd like to keep the old textmate goto file, as for some reason it successfully allows me to switch back to my previous file and peepopen doesn't (I don't use tabs at all), but I can no longer change the peepopen shortcut and have found no way to resurrect the old go-to-file shortcut.

Help?

**Comment by scottillogical** [comment]
What's strange is that it's not showing up in the bundle editor on one of my macs, but on the other it is.  It may be a textmate version issue.

**Comment by topfunky** [comment]
Go to ~/Library/Application Support/TextMate and remove PeepOpen from Bundles and/or Plugins. Restart TextMate and you should be good to go.

PeepOpen allows you to toggle between the last few files opened with PeepOpen. Files opened using TextMate aren't currently tracked (but it is planned).
