### ISSUE TITLE
PeepOpen very slow for a specific TextMate project…

### ISSUE THREAD

**Issue by nz** [topfunky/PeepOpen-Issues#129]
Hey Geoff,

Thanks a ton for PeepOpen, I've been waiting for something like this for years.

I've been seeing an issue with the latest version of PeepOpen that has even so far as caused me to disable it in TextMate for a few weeks because it's slowed me down so much.

When I first open PeepOpen with Cmd-T, it does the usual refresh progress bar, but then it shows an empty window with "Loading..." in the status bar. The process itself is sitting at 0% CPU and a reasonable 54M of memory. However, if I try to type, it jumps up to 130% or so, and keystrokes are noticeably laggy.

Typing various strings will occasionally give me some results back, but it's hard to figure out a pattern of what exactly is being returned, aside from them all being correct results. Which is to say, it's not trying to search my entire hard disk or anything. (I think.)

This is a pretty normal Rails app, with some 8,000 files, plenty of which would be ignored by the file and directory ignore patterns. Even when giving these results, I still see the "Loading..." message.

The truly mysterious thing to all of this is that PeepOpen is working just fine for me with MacVim and with other folders opened in TextMate. So is this really something specific to this particular collection of files in this particular folder?

I wish I had more concrete details to give you on this one. Maybe you could give me a few tips on how I could help track down whatever's going on? Is there some way for me to completely nuke all of my PeepOpen settings and caches and try again from scratch?

Thanks in advance.

—Nick

**Comment by topfunky** [comment]
I've recently implemented a better loading message that works better for large projects (in the next 0.2.4 release, coming soon). I'm also working on a faster search that searches a subset of files for a progressive search.

To nuke your settings, delete ~/Library/Preferences/com.topfunky.PeepOpen.plist

Or, go to PeepOpen Preferences, Advanced, and edit the regular expression for files or directories to ignore. It already ignores vendor/rails, but may need to ignore others if you have a local Bundler directory.

**Comment by topfunky** [comment]
Version 0.3.3 and greater have some speed fixes that make projects more usable (my demo project has 10,000 files and no longer has a multi-second lag on each key). Try it out (current version is 0.3.5).

**Comment by nz** [comment]
All looking great, and fwiw I haven't seen the original symptoms for quite a while now. Cheers!
