### ISSUE TITLE
BUG: Couldnt find files

### ISSUE THREAD

**Issue by noctivityinc** [topfunky/PeepOpen-Issues#130]
Everything was working peachy, then I added a new migration, hit Cmd + T, Cmd + R to refresh and got the following:

http://cl.ly/85afc1dde3eef1722b4f

**Comment by noctivityinc** [comment]
To add more details - I just added a simple model via script/generate model and then tried to refresh PeepOpen and this happened again.  Had to restart

**Comment by topfunky** [comment]
Similar bugs were fixed in 0.3.4. Are you still seeing this issue?
