### ISSUE TITLE
PeepOpen hanging on Reload

### ISSUE THREAD

**Issue by tobytripp** [topfunky/PeepOpen-Issues#132]
PeepOpen has been working great for me until today it started hanging as soon as it launched.  It displays the greyed-out progress bar as if reloading the project directory, but the progress bar never moves and I'm unable to enter any input.

Is there a data directory I can blow away?

I ran a sample of the application, you can find it here: http://gist.github.com/550120

**Comment by tobytripp** [comment]
It _seems_ to be an artifact of the project I'm in.  It doesn't happen in other projects.  Though, once it's locked up it stays that way until I kill it.

**Comment by topfunky** [comment]
The next 0.2.4 release will show better progress for large projects. It could be that it was still indexing the files, but that shouldn't take more than 20-30 seconds even for a project with 50k files or more.

How many files are in your project (approximately)?

**Comment by tobytripp** [comment]
3,978 files in the troublesome project.

**Comment by idlefingers** [comment]
Just had this happen with a project with <5k files in. 

I had a large file in a directory called 'data' which had modifications which had not been committed (in git). Once the changes were committed, peepopen finally reloaded quickly and successfully.

What seems really odd about this is that the 'data' directory the file was in was included in peepopen's directory ignore regex.

**Comment by keithpitty** [comment]
Curious. This just happened to me as well.

**Comment by keithpitty** [comment]
And all is good after I rebooted OS X. Curious though. If it happens again is there anything I can provide to help you debug, @topfunky?

**Comment by topfunky** [comment]
We just published 0.3.0 with a bunch of stability fixes. Give it a shot.

**Comment by tobytripp** [comment]
So far, so good.  Thanks!
