### ISSUE TITLE
PeepOpen will not open files.

### ISSUE THREAD

**Issue by rbazinet** [topfunky/PeepOpen-Issues#137]
I installed Peepopen to use with TextMate.  I can pull up the app with Cmd-T, no problem and then search for files.  Once I get the list of files back, I hit enter to open the file and nothing happens.  This has never worked.

Is this a bug anyone else sees?  I can't believe if it was that others wouldn't be reporting it.

Yes, I have the plugin installed in TextMate.  Yes I restarted TM.  I seems to work, just hitting enter or anything key for that matter will not open the target file.

Thanks,
   Rob

**Comment by mvidaurre** [comment]
I have exactly the same problem. I just installed today peepopen. I'm using TextMate Version 1.5.9 (1589). Snow Leopard 10.6.4

I wonder what could happen. I had reinstall twice PeepOpen without results

**Comment by mvidaurre** [comment]
I didn't mention. I am using PeepOpen 0.2.3

**Comment by topfunky** [comment]
First, debugging. Can you open files in TextMate from the terminal with:

```
open -a TextMate myfile.rb
```

If not, it appears that it could be a TextMate problem. I'm on "Minor Updates" in TextMate and show version 1.5.8 (1509), so I'm guessing that you are both on "Cutting-Edge" updates with TextMate.

Could you try downloading the latest stable version of TextMate and see if that fixes the problem? http://download.macromates.com/TextMate_1.5.9.dmg

**Comment by mvidaurre** [comment]
Yes, seems to be a change in an API that PeepOpen use. I'm able to open files from terminal without problem. And as I mentioned, my TextMate is Version 1.5.9 (1589) "Cutting-Edge".

**Comment by rbazinet** [comment]
OK, I tried to open from the command line and was able to w/o a problem.

I then figured I would installed the latest TextMate you linked to (1.5.9) and the problem still exists.  

I can try whatever else you need.

**Comment by rbazinet** [comment]
So this issue is not closed even after the most recent update.  Geoffrey, any progress with this?   It would be great to have a working installation of PeepOpen if possible.

**Comment by rbazinet** [comment]
I updated TextMate this morning to version 1.5 (1616) and PeepOpen now works great.  It looks like this was a TM issue, not PeepOpen.

**Comment by lardawge** [comment]
"It would be great to have a working installation of PeepOpen if possible."

I paid money for this and I kind of think it MUST work or I would like a refund... I am not in the habit of throwing money away.

Is there any news on this? I am using textmate 1.5.10 (1623) and 0.2.4 and have this problem. I would really love to actually get to use this thing but it seems plagued with bugs and no recent support... abandon-ware? Hmm, not the usual peepcode way.

**Comment by topfunky** [comment]
I wasn't able to reproduce this particular bug, but we've done a ton of work on stability in the just-released 0.3.0 version. Try again and we're always glad to refund if you don't find it useful.
