### ISSUE TITLE
Installation on Case Sensitive Systems

### ISSUE THREAD

**Issue by Fabs** [topfunky/PeepOpen-Issues#138]
I've installed peepOpen on Snow Leopard Case Sensitive HGFS for TextMate Version 1.5.9 (1510). What happens is that TextMate puts its plugins on the "PlugIns" folder (with capital letter "I")  while peepOpen installs itself on "Plugins" (lower case i).  I've spent some time trying to figure out why peepOpen would just "Not Work" till I've fount it out. 

It seems strange to me this TextMate behaviour of capitalizing the "I" since it generates the case sensitive/insensitive issues.

**Comment by topfunky** [comment]
That's painful. It sounds more like a bug with TextMate, but I'm not sure what their release schedule is for issues like that.

In the meantime, you can copy the PeepOpen.tmplugin to PlugIns and it should work.
