### ISSUE TITLE
~/Library/Application Support/TextMate/Plugins is called ~/Library/Application Support/TextMate/PlugIns instead

### ISSUE THREAD

**Issue by milzi234** [topfunky/PeepOpen-Issues#141]
I'm on TextMate 1.5.8 (1509), not the cutting edge version. When PeepOpen installs itself it winds up in the Plugins directory (and doesn't do anything), though according to TextMates Help Pages it should be called PlugIns (capital-I) (where it works all nice an cozy).

**Comment by topfunky** [comment]
I've fixed this in the repo and will include it in the next update. In the meantime, you can copy PeepOpen.tmplugin to the PlugIns directory.
