### ISSUE TITLE
PeepOpen stuck 'reading files'

### ISSUE THREAD

**Issue by jnewland** [topfunky/PeepOpen-Issues#143]
Screenshot:

<img src="http://files.jnewland.com/Open_File-20100928-122540.jpg" />

Using 2.4, survives restarts of PeepOpen and TextMate.

Happy to provide more info and help debug if possible.

**Comment by rud** [comment]
I see the exact same bug. Also got 0.2.4, TextMate 1.5.9 (1589). OSX 10.6.4.

Any known workarounds?

**Comment by jnewland** [comment]
Only one I could find was uninstalling, unfortunately.

**Comment by amiel** [comment]
I have the same issue.

**Comment by noctivityinc** [comment]
Me too.  Might need a refund at this point since its been months.

**Comment by noctivityinc** [comment]
HOLY CRAP I GOT IT TO WORK!!!

Try changing Run Git Diff Against to HEAD under SCM and see what happens.

**Comment by twmills** [comment]
I installed peepcode yesterday and it worked. But today no matter what I do, it hangs on reading files. Even changing"Run Git Diff Against" to HEAD doesn't work for me.

**Comment by twmills** [comment]
Oops, I obviously mean peepopen, not peepcode.

**Comment by topfunky** [comment]
PeepOpen 0.3.0 uses a legit background queue for loading files and should freeze less often, if at all. Get it from the "Check for Updates" menu item.

**Comment by amiel** [comment]
Yay, Thank you for the update!
