### ISSUE TITLE
Allow global shortcut to activate PeepOpen to last search path

### ISSUE THREAD

**Issue by tednaleid** [topfunky/PeepOpen-Issues#145]
It would be nice to have a global shortcut to activate peepopen, even if I don't have vim/textmate/emacs running and active.  Being able to cmd-T (or possibly a settable global alias) from any app and get peepopen to activate would be nice.  

It could default to the last directory root that it was using.

I'd think this would be (relatively) easy since peepopen is always running as a separate app.

**Comment by topfunky** [comment]
Interesting idea! Would it then open the file in your selected text editor, or navigate with the Finder?

**Comment by tednaleid** [comment]
I was thinking my selected text editor.  I use MacVim and sometimes don't have it running, or in the foreground, but I want to open up a file.  A large percentage of time, the file I want to open is in the project I'm actively working on.  The current work flow is either:
1. If MacVim isn't running: open up/cmd-tab to terminal, cd to my project directory and execute the vim command, then open up peepopen and get the actual file I want.

or 
1. MacVim is running: cmd-tab to macvim, make sure my project is the top vim window, open peepopen

Changing this to just <shortcut to open peepopen> would be nice.

**Comment by topfunky** [comment]
If you're already in the terminal, the easiest way to do this now might be to setup a shell alias or function. Run something like:

```
open 'peepopen://Users/my-user/path/to/project?editor=MacVim'
```

Or as a bash/zsh function:

```
function pn() {
  open "peepopen://`pwd`?editor=MacVim"
}
```

It will open the PeepOpen dialog and take you to MacVim with the selected file.

I think this is a great idea and I'm using it in my own shell now!

**Comment by tednaleid** [comment]
This.

That sounds like the perfect implementation,  I can script that myself and set the project path with an alias or even through Quicksilver/Launchbar to get my easy keystroke anywhere loading.

Just updated to 0.3.1 and am using the "peepopen://" functionality, works great.  Thanks for adding it.

**Comment by tednaleid** [comment]
Tweaked your aliases slightly to have a "current directory" alias and a generic function that I can pass any dir name into

```
function pn() {
    open "peepopen://$1?editor=MacVim"
}

alias pnc='pn `pwd`'
```

One other thing I just discovered (not sure if it's new to 0.3.1 or not) is that in Launchbar, I can choose a directory and then hit tab to "Send to" and pick the peepopen application, and peepopen uses that directory as my root for file searches.  

This, combined with the peepopen:// functionality gives me all the use that I was looking for through this issue.

**Comment by topfunky** [comment]
Awesome. I love LaunchBar's "send this file" feature. I didn't think of using it with PeepOpen.
