### ISSUE TITLE
Performance of Cmd-T, Cmd-V, Return is much slower than TextMate's native feature

### ISSUE THREAD

**Issue by edruder** [topfunky/PeepOpen-Issues#147]
Granted, PeepOpen is better, but it's so much slower than TextMate that I've often pasted a class or module name into the middle of a source file instead of into PeepOpen, then wondered why PeepOpen is taking so long to process the paste.

My project is somewhat large, but not crazy (I had to bump up PeepOpen's default number of files that it tracks).

Thanks.

**Comment by edruder** [comment]
Hmm. PeepOpen is often plenty fast. I'm not sure under what circumstances it slows down. I'll try to narrow this down.

**Comment by topfunky** [comment]
PeepOpen 0.3.0 was just released and has some performance improvements. Give it a shot with the "Check for Updates" menu item.
