### ISSUE TITLE
Project Specific Ignore Patterns

### ISSUE THREAD

**Issue by timuruski** [topfunky/PeepOpen-Issues#151]
It would be great if you could add project specific ignore patterns, it might be possible to pass the variables in through the bundle command. Maybe named like this:

$PO_IGNORE_FILES
$PO_IGNORE_FOLDERS

**Comment by jasonkuhrt** [comment]
Similar issue already here: https://github.com/topfunky/PeepOpen-Issues/issuesearch?state=open&q=ignore#issue/126, but I agree with you.

**Comment by topfunky** [comment]
Duplicate...closing. Will follow up on #126
