### ISSUE TITLE
Relatively high memory usage

### ISSUE THREAD

**Issue by vk77** [topfunky/PeepOpen-Issues#152]
Hi, just purchased Peeopen and was surprised with how much (relatively) memory it is using. I think > 50 MB is too much for such kind of software? Have you planned to pay attention to this area? Thanks.

**Comment by topfunky** [comment]
Due to our use of MacRuby, this really isn't something we can easily fix. RAM is cheap and Mac OS X does well with swap if you run out.

I agree that it would be an ideological improvement for it to be leaner. How much memory do you think it should use?

**Comment by wereHamster** [comment]
Heh, peepopen uses >150MB here!! It's the process with the single highest memory usage. Not even Chromium uses that much.

**Comment by topfunky** [comment]
Even at 150 MB, that's less than 4% of your available memory (assuming 4 GB). If PeepOpen is the most memory aggressive app you're running, then it sounds like you're pretty lean to start with.

Right now I'm planning to optimize performance over RAM usage. I'd rather have a really fast app that uses a bunch of memory than have an app that people have to continually wait for.

**Comment by benschwarz** [comment]
As an asides, Chrome will use far more ram than 150MB — It has a 'host' process then each tab within the browser will have a child process, areas that contain flash will also fork off to their own processes. 

So… currently on my machine chrome is using well over 1GB of memory. Not that hard to do.

**Comment by wereHamster** [comment]
.. that's why I said process and not application.

**Comment by wereHamster** [comment]
![image](https://img.skitch.com/20110527-teepwp1dmxb65b5812gws2b7fk.png)

Let's see if I can get it to use the full 4GB

**Comment by topfunky** [comment]
@wereHamster Curious...how long has that been running for? And is that on a single project or several?

**Comment by wereHamster** [comment]
Uptime is 28 days, I mostly work on two rails projects. One has ~2100 files (lots of plugins), the other one 309. But then there's lots of temporary files, maybe some of them aren't being ignored?
