### ISSUE TITLE
Hanging when refreshing files

### ISSUE THREAD

**Issue by suaron** [topfunky/PeepOpen-Issues#153]
After adding new files and pressing Command-R the program hangs.

http://dl.dropbox.com/u/3260528/Sample%20of%20PeepOpen.txt

http://dl.dropbox.com/u/3260528/Screen%20shot%202010-11-03%20at%2011.12.04%20AM.png

**Comment by topfunky** [comment]
We optimized refresh in 0.3.0 and now use a background queue for more reliable reloading. Try it out!
