### ISSUE TITLE
Freezed when switching from MacVim to Textmate.

### ISSUE THREAD

**Issue by antonysastre** [topfunky/PeepOpen-Issues#155]
Some how my PeepOpen app has frozen. I've tried re-installing without success. Also re-started the computer. 

The only thing I can think of that might have lead to it is that I was using it on MacVim and chose to switch to textmate. 

It's stuck in 'Reading files...' and nothing happends. I can still access the preferences and such though.

**Comment by topfunky** [comment]
PeepOpen 0.3.0 has a bunch of stability improvements that should fix this. Give it a shot with the "Check for Updates" menu item.
