### ISSUE TITLE
PeepOpen on MacVim does not work

### ISSUE THREAD

**Issue by jboner** [topfunky/PeepOpen-Issues#159]
It pastes in this piece of text into the currently open file instead of open the search window:

" ============================================================================
" Netrw Directory Listing                                        (netrw v140)
"   /Users/jboner/src/akka-stuff/akka-cloud/akka-cloud-cluster
"   Sorted by      name
"   Sort sequence: [\/]$,<core\%(.\d+)\=>,.h$,.c$,.cpp$,*,.o$,.obj$,.info$,.swp$,.bak$,~$
"   Quick Help: <F1>:help  -:go up dir  D:delete  R:rename  s:sort-by  x:exec
" ============================================================================
../
lib_managed/
src/
target/
.ensime

Tried both 5.2 SNAPSHOT and latest 7.3 version.

Any ideas?

**Comment by airblade** [comment]
Have you tried snapshot 55?  (Sorry, I couldn't quite tell from what you wrote.)

**Comment by jboner** [comment]
Works great. Thanks.
