### ISSUE TITLE
delay when starting Peepopen results in characters typed into TextMate document

### ISSUE THREAD

**Issue by timdiggins** [topfunky/PeepOpen-Issues#160]
I still get the problem of typing into my TextMate document when peepopen is slow to open on Cmd-T. I don't mind losing characters if necessary, but having them land into my documents is a real pain. 

this is not just when reindexing. it also happens when I switch back to TextMate from another app and immediately invoke PeepOpen  (0.2.4)

Is there no fix around the corner? (have been using this for a while)

PS - I tried but failed to find the original issue for this

**Comment by timdiggins** [comment]
Have just updated this one because I think I can narrow down when it is happening (as well as when the index has had to be rebuilt becuase of a crash):

When I switch back to TextMate from another app (e.g. terminal) and immediately invoke PeepOpen, there is the delay that allows characters to fall through into the document

**Comment by topfunky** [comment]
PeepOpen 0.3.0 uses a background queue and should respond more quickly. Give it a shot and tell me how it works for you.
