### ISSUE TITLE
Stuck Reading Files

### ISSUE THREAD

**Issue by scottwater** [topfunky/PeepOpen-Issues#161]
PeepOpen was working fine yesterday (first time re-installed it in a while) in Textmate. 

However, this morning when I type cmd+T it seems to be stuck trying to read the files.

Here is a screen shot: https://skitch.com/scottwatermasysk/rnx9s/stuck-reading

Shortly after the CPU spikes and stays there until I kill it. 

I have all the default settings including the number of files to load. 

Please let me know if you need any other info.

Version 0.2.4
Textmate

**Comment by topfunky** [comment]
We just pushed 0.3.0 which should fix this and other stability and freezing issues.
