### ISSUE TITLE
Freezes when trying to access files in TextMate

### ISSUE THREAD

**Issue by Bodacious** [topfunky/PeepOpen-Issues#163]
This error happens maybe once an hour or so

Project is only around 600 pages.

When I'm searching for a file, PeepOpen finds it but I can't click to access it. I hit ENTER but all that happens is the PO window closes.

Usually refreshing sorts this - still frustrating though as the file has not been renamed/moved.

**Comment by topfunky** [comment]
We just released version 0.3.0 with a bunch of stability improvements. Give it a shot.
