### ISSUE TITLE
MacVim not sending CWD to PeepOpen

### ISSUE THREAD

**Issue by fholgado** [topfunky/PeepOpen-Issues#166]
Guys,

I've had trouble using the latest MacVim snapshot (55) and PeepOpen. For some reason, it's not sending the CWD properly to PeepOpen.

I've changed one line in peepopen.vim and it seems to fix the issue. Here is the change:

<pre>
  function s:LaunchPeepOpenViaVim()
   let cwd = getcwd()
   silent exe "!open -a PeepOpen " . shellescape(cwd)
  endfunction   
</pre>

I've changed the cwd variable to use the getcwd() function directly and it now seems to be working. Any ideas as to what may be going on?

Thanks!

**Comment by topfunky** [comment]
I'm not sure what's causing that, but I'm glad you got it to work. Try the latest PeepOpen for better multi-editor search with a custom URL scheme. 

See also #87 for an alternate MacVim config.
