### ISSUE TITLE
Forces Nvidia GPU Use

### ISSUE THREAD

**Issue by paulbeattie** [topfunky/PeepOpen-Issues#167]
On the 2010 MacBook Pro's when PeepOpen is used it forces a switch to the Nvidia GPU. When finished it doesn't release the GPU so the Nvidia GPU is kept active until quit.

**Comment by topfunky** [comment]
We added an option in Preferences > Advanced to "Use Core Animation". If you uncheck this and restart PeepOpen it will not use the Nvidia GPU.
