### ISSUE TITLE
Add option to limit fuzzy search to file names

### ISSUE THREAD

**Issue by gaiottino** [topfunky/PeepOpen-Issues#168]
Hi,

I was trying to use Peepopen in replace of TMs Go to File... but removed it once I realized that there is no way to limit the search to filenames only. I normally open all my files with CTRL+T in TM and where typing 'campcon' would return 3 files and I could quickly select which one I wanted, Peepopens version returns 50! files since it lists all the files in the directory structure matching the search making it unusable for me.

Please add an option to only include file names in the search.

**Comment by topfunky** [comment]
The current algorithm puts a preference on filenames, so it will try to match a filename with your search before looking for matching directories. So they should be at or near the top in either case. Does this solve the problem for you?

**Comment by gaiottino** [comment]
This works alot better. Thanks.

I would still request an option to ignore folders completely to reduce the size of the list but this is a step in the right direction making it usable again.
