### ISSUE TITLE
Freezed!

### ISSUE THREAD

**Issue by antonysastre** [topfunky/PeepOpen-Issues#169]
The app is freezed on Refreshing files either on TextMate or MacVim plugins.
I've tried removing and re-installing and deleting ~/Library/Preferences/com.topfunky.PeepOpen.plist

I can access the preferences though but it just doesn't get any files.

**Comment by topfunky** [comment]
PeepOpen 0.3.0 has just been released and has a bunch of stability improvements. Try it out with the "Check for Updates" menu item.
