### ISSUE TITLE
Feature Request:  RubyMine Support

### ISSUE THREAD

**Issue by raphaelcosta** [topfunky/PeepOpen-Issues#174]
Maybe PeepOpen could be compatible with Rubymine

**Comment by topfunky** [comment]
PeepOpen 0.3.0 supports a custom URL scheme, so a Rubymine plugin could be written without much work.

[Custom URL Scheme Documentation](http://peepcode.com/system/uploads/2010/PeepOpen-Help/editors%20-%20custom.html)

**Comment by derekprior** [comment]
Please see: http://prioritized.net/blog/using-peepopen-with-rubymine/

**Comment by topfunky** [comment]
@derekprior Thanks for the work. I'll put this in the next release of the app.
