### ISSUE TITLE
Crash Reports

### ISSUE THREAD

**Issue by topfunky** [topfunky/PeepOpen-Issues#176]
If you experience a crash with PeepOpen and want to report it, post a comment on this ticket.

As always, any description of what you were doing while it crashed would be helpful.

We may integrate optional automated crash reporting in the future.

**Comment by nanno77** [comment]
I can't get it to start it looks like I get the following errors in the console.

```
 3/8/11 10:48:57 AM [0x0-0x5f05f].com.topfunky.PeepOpen[740]    LLVM ERROR: Cannot yet select: 0x103865010: f64 = bit_convert 0x103865410 [ORD=347] [ID=7]
 3/8/11 10:48:57 AM [0x0-0x5f05f].com.topfunky.PeepOpen[740]      0x103865410: i64 = and 0x103883210, 0x103881310 [ORD=346] [ID=6]
 3/8/11 10:48:57 AM [0x0-0x5f05f].com.topfunky.PeepOpen[740]        0x103883210: i64,ch = CopyFromReg 0x103211338, 0x103865f10 [ORD=346] [ID=5]
 3/8/11 10:48:57 AM [0x0-0x5f05f].com.topfunky.PeepOpen[740]          0x103211338: ch = EntryToken [ORD=346] [ID=0]
 3/8/11 10:48:57 AM [0x0-0x5f05f].com.topfunky.PeepOpen[740]          0x103865f10: i64 = Register %reg16384 [ORD=346] [ID=1]
3/8/11 10:48:57 AM  [0x0-0x5f05f].com.topfunky.PeepOpen[740]        0x103881310: i64 = Constant<-4> [ORD=346] [ID=2]
3/8/11 10:48:57 AM  com.apple.launchd.peruser.501[315]  ([0x0-0x5f05f].com.topfunky.PeepOpen[740]) Exited with exit code: 1
```

**Comment by topfunky** [comment]
It looks like you're on a new MacBook Pro. The MacRuby team is aware of the issue on the newest CPU and is working fervently on a fix. I'll release an update of the app as soon as they have a version ready.

In the meantime, email boss@topfunky.com if you would like to revert to 0.2.4.
