### ISSUE TITLE
faster engine

### ISSUE THREAD

**Issue by wilkerlucio** [topfunky/PeepOpen-Issues#178]
Hi, I like peepcode a lot, but I'm now working in a bigger project with a lot of files, and Peepcode got unusable... In peepopen I have just 2040 files in index, and it's slow... I know it can be better because I'm now using Command-T in Vim instead of PeepOpen, it's currently indexing all files (7824 files) and it still very fast. I mean you can try to inspect source and see how it does this, because its really nice! Here is the link to Commant-T plugin: http://www.vim.org/scripts/script.php?script_id=3025

**Comment by topfunky** [comment]
We just pushed an 0.3.0 release which is a bit faster. But we're focusing on speed for the next release and hope to make it as fast as possible.

**Comment by topfunky** [comment]
Version 0.3.3 and greater include more speed fixes. Try it out (current version is 0.3.5).
