### ISSUE TITLE
Crashes on OS X Lion (10.7)

### ISSUE THREAD

**Issue by lucashungaro** [topfunky/PeepOpen-Issues#182]
The app crashes on load on Mac OS X Lion Developer Preview. Here's the crash log: https://gist.github.com/843874

**Comment by topfunky** [comment]
I haven't tried Lion but will work on installing it to try this out. As of PeepOpen 0.3.0 we're using MacRuby 0.9, which may have some improvements on Lion.

**Comment by lucashungaro** [comment]
Nice! Looking forward to it, PeepOpen became an essential tool on my workflow. Thanks.

**Comment by raphaelcosta** [comment]
Doesnt work for me too

**Comment by lucashungaro** [comment]
Removed it with AppCleaner then downloaded the dmg (I was just "installing" the .app before) and it is working.

Weird, but nice. :)

**Comment by raphaelcosta** [comment]
worked for me! Thanks!

**Comment by topfunky** [comment]
Could be related to the MacRuby LLVM issue in the 0.3.1 version. I'll try to get a copy of Lion before the official release and try it out.

**Comment by dmilith** [comment]
please fix it.. it makes my TM handicapped..

**Comment by dmilith** [comment]
is it possible to write ruby part of PeepOpen code in different language? I could help! Die ruby die!

**Comment by raphaelcosta** [comment]
Please, read the history of ticket. Just uninstall and install again..

**Comment by dmilith** [comment]
I probably have old version of PeepOpen.. from where I can download current compiled one? (note: no xcode yet on Lion so I can't compile it here)

**Comment by raphaelcosta** [comment]
from your account in peepcode

**Comment by dmilith** [comment]
I've taken PeepCode from SL and it works :}. Anyway:
"No account was found with the email address you requested." (tried both my emails). But I actually buyed PeepCode some time ago (and have receipt to prove it)

It might be that I've never created PeepCode account before

If I remember correctly, there were no accounts on peepcode.com that time. I have only links on email to older version of PeepCode

**Comment by topfunky** [comment]
We definitely hope to support Lion, but it hasn't been officially released yet and we don't have a copy.

You can signup at PeepCode and your previous orders will be automatically linked: https://peepcode.com/signup

Or email peepcode@topfunky.com and we're glad to help.

**Comment by topfunky** [comment]
I just upgraded to the final version of Lion and everything is working correctly. Open this ticket again with details if you're still seeing a crash.
