### ISSUE TITLE
PeepOpen Crashes when there is a .rvmrc file in the project root #bug

### ISSUE THREAD

**Issue by brupm** [topfunky/PeepOpen-Issues#184]
File contents are:

rvm 1.9.2

As soon as I remove the file it works perfectly.

**Comment by topfunky** [comment]
This is an odd bug. I'm using PeepOpen with a bunch of .rvmrc projects and haven't seen this crash. Can you try with the newest PeepOpen 0.3.0 and see if it still crashes?

**Comment by shad** [comment]
Was excited to see 0.3, but unfortunately I'm still seeing this on 0.3.0.  Here's the contents of my .rvmrc in case it helps.

```
rvm --create use ree-1.8.7@companyname > /dev/null
```

**Comment by shad** [comment]
I also simplified my file to the following and still see the issue.

```
rvm ree-1.8.7@companyname
```

**Comment by topfunky** [comment]
This is a duplicate with ticket #140. Will comment and fix there.
