### ISSUE TITLE
0.30 Fails on start on OS X

### ISSUE THREAD

**Issue by scottwater** [topfunky/PeepOpen-Issues#185]
I just downloaded and installed 0.30 on OS X 10.6.6.

When I execute it, at first I get OS X's warning about a new app from the internet. I click OK and I see nothing. If I try to restart it again, I still see nothing. 

Executing open /Applications/PeepOpen.app in terminal displays the following message:

```
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/PeepOpen.app.
```

Thanks,
Scott

**Comment by dedene** [comment]
I'm having the same problem.

**Comment by dougjohnston** [comment]
Same problem here.

**Comment by nanno77** [comment]
Yep. Same here.

**Comment by esparkman** [comment]
Same here as well.

**Comment by topfunky** [comment]
Version 0.3.1 was just released with a newer version of MacRuby that should work on the latest MacBook Pro. Run "Check for Updates" or get it here:

https://peepcode.com/products/peepopen
