### ISSUE TITLE
Search performance drastically decreased with 0.3

### ISSUE THREAD

**Issue by mhenrixon** [topfunky/PeepOpen-Issues#186]
Hi,

Thank you for an otherwise excellent product. The problem I have is that every time I open the search with cmd+t it opens fast. Soon as I type something though I have to wait for a few seconds before peepopen responds again. I have tried pretty much everything including like the release note said to reinstall the plugin. 

What can I do now? 
Should I downgrade?

Forgot to mention that it's an incredibly small rails 3 app I am working on and I haven't changed any defaults.

Edit 2: I set the number of files to track to 500 but I still have this problem. Soon as I hit the textbox to begin a search it freezes/works for 3-5 seconds which makes the application kind of unusable! :(

Edit 3: Tried upgrading to MacRuby 0.9 but that didn't do anything either. Uninstalling it now.

**Comment by mhenrixon** [comment]
I have uninstalled peepopen and all is well. Any possibility of getting this fixed?

**Comment by topfunky** [comment]
That's confusing, especially with a smaller project.

A delay of half a second should be expected, but 3-5 seconds is quite a lot.

Are you using an SSD or standard hard disk? Are the files on a local drive or network?

**Comment by mhenrixon** [comment]
I'm on a MBP with standard disk. Don't have any other peformance issues and the files are located on local drive. Noteworthy is that performance was great until version 0.3 so something in the last release decreased performance to uselessness.

**Comment by mhenrixon** [comment]
Then can I please get the previous version of peepopen so that I may at least use the product I payed for?

**Comment by topfunky** [comment]
Yes, email boss@topfunky.com and I'll be glad to send you a link to the previous version.
