### ISSUE TITLE
PeepOpen is not starting

### ISSUE THREAD

**Issue by dedene** [topfunky/PeepOpen-Issues#188]
I wanted to install PeepOpen on a clean, new MacbookPro, but it refuses to start. In the system log, I can find the following:

6/03/11 17:36:56    [0x0-0x39039].com.topfunky.PeepOpen[333]    LLVM ERROR: Cannot yet select: 0x10600fc10: f64 = bit_convert 0x106010010 [ORD=347] [ID=7]
6/03/11 17:36:56    [0x0-0x39039].com.topfunky.PeepOpen[333]      0x106010010: i64 = and 0x106029010, 0x10601e710 [ORD=346] [ID=6]
6/03/11 17:36:56    [0x0-0x39039].com.topfunky.PeepOpen[333]        0x106029010: i64,ch = CopyFromReg 0x103508168, 0x106017510 [ORD=346] [ID=5]
6/03/11 17:36:56    [0x0-0x39039].com.topfunky.PeepOpen[333]          0x103508168: ch = EntryToken [ORD=346] [ID=0]
6/03/11 17:36:56    [0x0-0x39039].com.topfunky.PeepOpen[333]          0x106017510: i64 = Register %reg16384 [ORD=346] [ID=1]
6/03/11 17:36:56    [0x0-0x39039].com.topfunky.PeepOpen[333]        0x10601e710: i64 = Constant<-4> [ORD=346] [ID=2]
6/03/11 17:36:56    com.apple.launchd.peruser.501[154]([0x0-0x39039].com.topfunky.PeepOpen[333]) Exited with exit code: 1

Any idea what the problem could be?

Thanks and regards,
Peter

**Comment by topfunky** [comment]
PeepOpen 0.3.1 was built with a newer version of MacRuby that should work on the latest MacBook Pro. Run "Check for Updates" or get it here:

https://peepcode.com/products/peepopen
