### ISSUE TITLE
XCode 4 LLVM a problem?

### ISSUE THREAD

**Issue by johnpaulashenfelter** [topfunky/PeepOpen-Issues#189]
I've got a brand-new Sandybridge Macbook Pro and I'm having trouble installing PeepOpen. Doubleclicking silently fails. Opening from command line gives

LSOpenURLsWithRole() failed with error -10810 for the file /Applications/PeepOpen.app.

Detailed info from log
3/7/11 11:20:34 AM  [0x0-0x40040].com.topfunky.PeepOpen[2877]   LLVM ERROR: Cannot yet select: 0x10680e210: f64 = bit_convert 0x10680e610 [ORD=347] [ID=7]
3/7/11 11:20:34 AM  [0x0-0x40040].com.topfunky.PeepOpen[2877]     0x10680e610: i64 = and 0x106831e10, 0x106830310 [ORD=346] [ID=6]
3/7/11 11:20:34 AM  [0x0-0x40040].com.topfunky.PeepOpen[2877]       0x106831e10: i64,ch = CopyFromReg 0x1032112f8, 0x106820110 [ORD=346] [ID=5]
3/7/11 11:20:34 AM  [0x0-0x40040].com.topfunky.PeepOpen[2877]         0x1032112f8: ch = EntryToken [ORD=346] [ID=0]
3/7/11 11:20:34 AM  [0x0-0x40040].com.topfunky.PeepOpen[2877]         0x106820110: i64 = Register %reg16384 [ORD=346] [ID=1]
3/7/11 11:20:34 AM  [0x0-0x40040].com.topfunky.PeepOpen[2877]       0x106830310: i64 = Constant<-4> [ORD=346] [ID=2]
3/7/11 11:20:34 AM  com.apple.launchd.peruser.501[96]([0x0-0x40040].com.topfunky.PeepOpen[2877]) Exited with exit code: 1

I am running the XCode 4 GM 2 release instead of XCode 3 like on my other machines. Could that be the prob? Happy to work with a new build to help solve it fwiw.

**Comment by topfunky** [comment]
I used a nightly build of MacRuby that should be compatible with Sandybridge. Try the latest PeepOpen 0.3.1.

**Comment by johnpaulashenfelter** [comment]
Seems to work great for me. I'm on 10.6.7 fwiw and using TextMate.
