### ISSUE TITLE
Sort order incorrect when searching

### ISSUE THREAD

**Issue by noctivityinc** [topfunky/PeepOpen-Issues#19]
When you search for a document, the closest matches should be the documents that have the phrase being typed CLOSE together.  For example, in my Rails app I have a namespace called Public, and therefore folders called Public.  I also have a layout called public.html.haml.

Now, when I search for "publichtmlhaml" I expect, like TM, that public.html.haml would be the FIRST on the list.  Unfortunately, it was WAY down there.    The first one coming up is "public/index.html.haml"

It's possible that spaces support will help fix this, as you can search for groups of words that are closest together based on the phrases entered.

**Comment by topfunky** [comment]
Fixed in today's 0.1.8 release. Filename matches now sort higher than path matches, which should provide better behavior.

I want this to be the best fuzzy matcher in existence and will continue to improve it as other edge cases are reported.
