### ISSUE TITLE
.rvmrc lockup in 0.3.0

### ISSUE THREAD

**Issue by shad** [topfunky/PeepOpen-Issues#190]
I know this was an issue in 0.2.x, but I'm still seeing peepopen lock up when I have a .rvmrc file.  If I turn off the SCM metadata, then all is well, but as soon as I turn it back on, I'm seeing the freeze.  It occurs as soon as I open peepopen.

Note, I'm seeing this problem even when the .rvmrc file is totally empty.  Any help would be appreciated.

**Comment by topfunky** [comment]
Thanks for the report. I'll try to recreate it with 0.3.0.
