### ISSUE TITLE
Migration Assistant - PeepOpen Fails to Start - No Error

### ISSUE THREAD

**Issue by esparkman** [topfunky/PeepOpen-Issues#192]
I purchased a new macbook pro today and ran migration assistant, when I try and run PeepOpen on the new macbook I tries to open then nothing happens. Not sure what the issue could be.

**Comment by esparkman** [comment]
Quick update. Reinstalled OSX Snow Leopard 10.6.6 clean. PeepOpen will not open on a clean install either. I am running the newest Quad Core macbook pro.

**Comment by topfunky** [comment]
There was an issue with the CPU in the latest MacBook Pro. It has been fixed in PeepOpen 0.3.1. Run "Check for Updates" or download from PeepCode:

https://peepcode.com/products/peepopen

**Comment by esparkman** [comment]
topfunky: thanks for the fix!
