### ISSUE TITLE
textmate: sometimes... PeepOpen only searches /public folder

### ISSUE THREAD

**Issue by whatbird** [topfunky/PeepOpen-Issues#193]
this is a weird one, and i'm sure it was introduced when i upgraded to 0.3.0 [from 0.2.4].

EDITED:

sometimes when i'm using PeepOpen i only get files from the public folder [of my rails project] [even if i PeepOpen>reload files]. 

this seems to happen when i'm working on files in the /public folder, or have one selected there. if i select another file in the project drawer (or change to a different file) and open PeepOpen again... all my project files are now searchable.

thanks,
-c

**Comment by topfunky** [comment]
This sounds like an issue with PeepOpen finding the project root. Is the project in a Git or Subversion repository? There is an issue where .svn directories in every subdirectory were confusing the app. We hope to fix it in a future release.

**Comment by whatbird** [comment]
this is a git project. let me know if any more details would be useful.

**Comment by whatbird** [comment]
ok this got worse for me.

now, when i open textmate and CMD-T, PeepOpen works correctly exactly once.

all subsequent attempts to locate file search only the public, test, and vendor folders [it seems]. also, the root of the project moves up one to the parent of the initial root. 

i'm on 0.3.1. i'm not using a textmate project file.

**Comment by whatbird** [comment]
ok, i may have a clue:

possibly: the reason that the only thing that shows up seems to be vendor etc, is that the project root gets moved up to the parent and the "vendor/rails" exception no longer works. i do have rails vendored in this app, and that is maxing out the 3000 max files that was set in the PeepOpen prefs.

still works right the first time. then re-catalogs.

**Comment by topfunky** [comment]
This sounds like the bug in 0.3.1 that was fixed in 0.3.2

Run "Check for Updates" and re-install the TextMate plugin after installation (and restart TextMate).

**Comment by whatbird** [comment]
still doin' it

**Comment by topfunky** [comment]
I'll try to reproduce this error. In the meantime, you could increase the number of files indexed by PeepOpen. Drag it up to 3,500 or "All".

**Comment by whatbird** [comment]
i fixed it by ignoring rails with:  ^.*vendor\/rails

so, i'm productive, but the bug persists.

thanks for being on top of all this.
