### ISSUE TITLE
In Fullscreen, mac menubar should not be revealed with peep-open

### ISSUE THREAD

**Issue by jasonkuhrt** [topfunky/PeepOpen-Issues#194]
One of the reasons peep-open is great is the ui-on demand aspect. It has what you need and nothing more, and as soon as you're file is found, it's out of the way automatically. Great.

But using an editor in fullscreen reveals an ugly moment in this experience. The OSX menubar is revealed. See the following screenshot to see exactly what I mean [http://d.pr/lwDf](http://d.pr/lwDf).

It would be great if calling peepopen did not disturb the full-screen experience.

This issue will be more pressing with Lion (in a sense) since positive-experience full-screen apps will be more of an expectation than it may be now.

What are your thoughts on this? Is it easy to solve? if so would you consider it high-priority or something to solve in a year's time? Etc...

Thanks

**Comment by topfunky** [comment]
- Go to PeepOpen Preferences > Advanced 
- Uncheck "Show in Menu Bar". 
- Quit PeepOpen.
- Activate PeepOpen from MacVim. It should not show the global menu bar any more.
- You can access the PeepOpen menu and preferences from the sprocket icon on the side of the search field.

**Comment by jasonkuhrt** [comment]
Hmm.. I've removed it from my menubar but the described behaviour remains. Actually you can see in my screenshot above that peepopen is not in the menubar. My current mapping in vim for peepopen is:

```
map <D-t> <Plug>PeepOpen
```

**Comment by topfunky** [comment]
You're right...I tried it in MacVim right now and saw the behavior you reported.

It worked correctly in full screen mode in "that other editor."

Trying other utility apps gives mixed results. LaunchBar doesn't show the menu bar, but Alfred does.

My guess is that either it's a MacVim issue or requires an obscure Cocoa API configuration that I haven't yet discovered.

**Comment by jasonkuhrt** [comment]
Ok. Now we've confirmed the behaviour. That's one step resolved at any rate. Thanks for the update topfunky.
