### ISSUE TITLE
App does not launch on my new Macbook Pro

### ISSUE THREAD

**Issue by ghost** [topfunky/PeepOpen-Issues#195]
The application would not start on my machine, so I tried launching from the Terminal and this is what I get :

LSOpenURLsWithRole() failed for the application /Applications/PeepOpen.app with error -10810.

I'm running 10.6.6.

**Comment by topfunky** [comment]
Apparently this is an issue with the latest MacRuby. They are aware of it and are working on a fix right now. I hope to publish an update within the next few days that will use their fix for the newest MacBook Pro CPU.

Email boss@topfunky.com for a link to the older version of PeepOpen if you would prefer to use that in the meantime.

**Comment by ghost** [comment]
Thanks for the heads up.

**Comment by topfunky** [comment]
I just released 0.3.1 with a fixed version of MacRuby that should work now.

Run "Check for Updates" or download again from PeepCode: https://peepcode.com/products/peepopen

**Comment by ghost** [comment]
Cool, it works! Thanks.

On Mon, Mar 21, 2011 at 9:47 PM, topfunky <
reply@reply.github.com>wrote:

> I just released 0.3.1 with a fixed version of MacRuby that should work now.
> 
> Run "Check for Updates" or download again from PeepCode:
> https://peepcode.com/products/peepopen
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/topfunky/PeepOpen-Issues/issues/195#comment_901251

## 

---

Q: Why is this email five sentences or less?
A: http://five.sentenc.es http://three.sentenc.es
