### ISSUE TITLE
App Crashes on Launch on new 15" MBP

### ISSUE THREAD

**Issue by bgentry** [topfunky/PeepOpen-Issues#197]
I'm trying to get PeepOpen up and running on a brand new 15" Mac 2011 (quad core i7). When trying to open the app, it appears that nothing happens (doesn't show up in processes list). When trying to launch the executable manually from terminal, I see the following:

bgentry$ /Applications/PeepOpen.app/Contents/MacOS/PeepOpen 
LLVM ERROR: Cannot yet select: 0x104814810: f64 = bit_convert 0x104814c10 [ORD=347] [ID=7]
  0x104814c10: i64 = and 0x104835c10, 0x10482bb10 [ORD=346] [ID=6]
    0x104835c10: i64,ch = CopyFromReg 0x102f8c8f8, 0x104815710 [ORD=346] [ID=5]
      0x102f8c8f8: ch = EntryToken [ORD=346] [ID=0]
      0x104815710: i64 = Register %reg16384 [ORD=346] [ID=1]
    0x10482bb10: i64 = Constant<-4> [ORD=346] [ID=2]

Let me know what additional information I can provide you to help debug this problem.

**Comment by topfunky** [comment]
This is an issue with MacRuby and the new i7 processor. An update from MacRuby is expected sometime this weekend and we'll release a PeepOpen update when it's ready.

**Comment by rud** [comment]
This specific error is fixed in the 0.3.2 release, though a manual re-install of PeepOpen is necessary. The installation file for this version is called peepcode-peepopen-032-code.zip

**Comment by bgentry** [comment]
Works beautifully, thanks a bunch!
