### ISSUE TITLE
PeepOpen not working with directories

### ISSUE THREAD

**Issue by Jayphen** [topfunky/PeepOpen-Issues#198]
Opening a directory in Textmate will cause PeepOpen to show the following error every time it's opened: http://d.pr/yV3I

Creating a project in Textmate results in PeepOpen not opening at all.

**Comment by topfunky** [comment]
Unfortunately, PeepOpen doesn't work with TextMate projects (only files on disk in a single directory).

We've made some error messages clearer in the development version and will publish those with the next release of PeepOpen.

**Comment by Jayphen** [comment]
Hey topfunky, that does address the issue I mentioned with projects, but the first error I posted a screenshot of came up when I opened a normal directory of files in Textmate.

**Comment by topfunky** [comment]
We released 0.3.2 a week ago and it fixed similar problems for a bunch of people. Try it out and reopen this ticked if you still see the error.
