### ISSUE TITLE
TextMate Problem 

### ISSUE THREAD

**Issue by sunny36** [topfunky/PeepOpen-Issues#2]
For me it doesn't seem to work on TextMate 1.5.9 (1510) works fine on MacVim. 

I see the bundle gets installed at 
~/Library/Application Support/TextMate/Bundles
but when I type Cmd-T I get the same old TextMate dialog.

**Comment by topfunky** [comment]
Due to how TextMate bundles work, you need to have at least one file open (i.e. source code showing in the editor pane). After this, it should fire off PeepOpen instead of the TextMate dialog.

Or (for our information) try selecting it from TextMate's Bundles menu: PeepOpen -> Open File

**Comment by sunny36** [comment]
You were right at least one file has to be open. 
It works now. Thanks.

**Comment by topfunky** [comment]
No problem.
