### ISSUE TITLE
Add a documentation for Command-T support in MacVim.

### ISSUE THREAD

**Issue by takaaki** [topfunky/PeepOpen-Issues#20]
This is how users use Command-T in MacVim. The downside of this is to kill the default Command-T function, which creates a new tab. But `<Leader>p` is often used with project drawer-type plugins such as [NERDTree](http://www.vim.org/scripts/script.php?script_id=1658) and [Projects](http://www.vim.org/scripts/script.php?script_id=69).

```
if has("gui_macvim")
  macmenu &File.New\ Tab key=<nop>
  map <D-t> <Plug>PeepOpen
end
```

**Comment by topfunky** [comment]
Several other plugins use <Leader>t, so I didn't want to clobber that. But as I don't use tabs (and maybe others don't either), it would be useful as Cmd-t.

Your snippet has been added as a comment in peepopen.vim in the 0.1.8 release.

Thanks!

**Comment by chalmagean** [comment]
this diesn't seem to work... any idea why ? it just opens a new tab

**Comment by topfunky** [comment]
If it opens in a tab, try using MacVim snapshot 52 or newer with these preferences:

```
http://peepcode.com/system/uploads/2010/PeepOpen-Help/editors%20-%20macvim.html
```

**Comment by andyduncan** [comment]
This doesn't appear to work anymore, even with the preferences listed.

**Comment by topfunky** [comment]
@andyduncan Which snapshot version of Vim did you experience the error on?

Does Console.app show any messages about MacVim or PeepOpen?

**Comment by andyduncan** [comment]
@topfunky I'm running snapshot 61. I don't get any console logs about macvim or peepopen.
