### ISSUE TITLE
Just upgraded to 0.3.1 and it is now unusable - showing files from many different folders

### ISSUE THREAD

**Issue by chrishomer** [topfunky/PeepOpen-Issues#200]
I just moved to 0.3.1 and now peepopen contains completely unrelated files.  It used to be peepopen confined itself to the folder I had opened in textmate.  

Running
PeepOpen 0.3.1
TextMate 1.5.10 (1631)

Any idea?

Thanks.

**Comment by olt** [comment]
I can confirm that (PeepOpen 0.3.1 and TextMate 1.5.10 on Mac OS X 10.6.6 and .7 here).

PeepOpen always shows files from my home dir and not the project dir. I already removed the .plist file, the Library/Cache stuff and the TextMate plugin. Is there anyway to downgrade?

**Comment by topfunky** [comment]
Here are temporary links to older versions:

```
http://dl.dropbox.com/u/1989993/PeepOpen-0.2.4.dmg

http://dl.dropbox.com/u/1989993/PeepOpen-0.3.0.dmg
```

Can you provide any other details about the project? Is it a Git project? Is it contained in a single directory? Is it on a local disk or a separate volume?

**Comment by chrishomer** [comment]
it is in ~/Sites/project
it's a git directory.
Sites contains numerous projects with git directories.

The contents of the peepopen results seem to be all the projects in the Sites directory (limited to 3000 files - my setting in prefs).

Thanks for your help!

**Comment by chrishomer** [comment]
I think I just closed this by mistake. Sorry about that.

**Comment by olt** [comment]
For me it is `~/dev/project` a mercurial repo with README.txt file. I opened TextMate with `mate ~/dev/project`, so it is the whole directory and not a custom project. PeepOpen shows me files from my home (.dropbox, etc.).

It is a new brand new MPB 13" if that matters? (Seems I can't use the older versions in this case :/)

**Comment by olt** [comment]
Ok, I just created a new "project":

```
[~]% mkdir foo
[~]% cd foo
[~/foo]% touch bar
[~/foo]% mate .
[~/foo]% hg init
[~/foo]% mate .
[~/foo]% touch README
[~/foo]% mate .
```

It always indices my home dir if I press cmd-T and cmd-R in TextMate.

Console says:

```
22.03.11 19:10:14   TextMate[819]   OakprojectController (PeepOpen), sending url peepopen:///Users/olt/foo?editor=TextMate to NSWorkspace
```

**Comment by texel** [comment]
Same thing happening in MacVim- gets to 2100 files and then the app crashes. Version 0.3.0 still works fine. I have crash logs too if you need any help diagnosing this.

**Comment by timdiggins** [comment]
ditto. with 0.3.1 TextMate is indexing my home directory instead of the project directory

**Comment by ghost** [comment]
Same thing here. 0.3.1 shows files in ~/ instead of the current project directory (my projects are in ~/projects/PROJECT_NAME)

My home directory itself isa git repo (with a ~/.git) folder. If I rename ~/.git/ to ~/.git-old/ the problem goes away. 

This was not an issue in 0.3.0

HTH

**Comment by chrishomer** [comment]
In case it helps, none of the directories above my project directory are git repos.

**Comment by briancavalier** [comment]
+1 I am seeing the same behavior in Textmate after upgrading to 0.3.1 with svn and git projects in any subdir of my ~/Sites dir.

**Comment by topfunky** [comment]
I've been unable to reproduce the bug yet but am tackling it today. I've heard several reports of people experiencing the same thing.

**Comment by chrishomer** [comment]
Thanks! I am happy to get on skype and share my screen if that will help explore the problem.

Chris Homer
skype: atomicvaporinc

On Mar 23, 2011, at 8:50 AM, topfunky wrote:

I've been unable to reproduce the bug yet but am tackling it today. I've heard several reports of people experiencing the same thing.

## 

Reply to this email directly or view it on GitHub:
https://github.com/topfunky/PeepOpen-Issues/issues/200#comment_908113

**Comment by philcrissman** [comment]
Same issue as above; my projects are in ~/Projects, and rather than showing files from ~/Projects/wherever/, PeepOpen lists everything (up to 3000 files) from ~/Projects/.

Also TextMate 1.5.10; Mac OS 10.6.7.

Edit: just confirmed that reverting to 0.3.0 did fix the issue.

**Comment by jmreidy** [comment]
I've run into this issue since updating; seeing it with both TextMate and MacVim.

**Comment by smtm** [comment]
Same here - makes peep open quite unusable ..

**Comment by smtm** [comment]
BM5k s Tipp seems to be a Workaround 
https://github.com/topfunky/PeepOpen-Issues/issues/200/#issue/200/comment/905415

Back to normal blood level - not having peep open stresses me to no end, addictive product there @topfunky ;-)

**Comment by granth** [comment]
Same as BM5k. My home directory is in git. If I `mv ~/.git ~/.git-tmp` PeepOpen starts working again. This wasn't a problem before 0.3.1.

**Comment by philcrissman** [comment]
Me as well; my ~/Projects directory also had a .git directory in it, and renaming it fixed the issue with 0.3.1.

That said, like others have mentioned... this wasn't an issue in <= 0.3.0. 

In my case, I don't actually need my entire projects directory stashed in one huge git repo (the ~/Projects/.git/ must have been sitting there, unused, for a long time), but I would think one should be able to have the parent directory in source control, if needed, without messing up PeepOpen. :-)

**Comment by keithpitty** [comment]
This is a problem for me as well in one scenario.  This is when I'm working on such a large project that the only responsive way of using TextMate is to open separate windows for subdirectories e.g. one for lib, one for app etc.  So each of these windows is not open at the directory level where .git exists.  That seems to be the nub of the problem introduced with PeepOpen 0.3.1, as far as I can see.

I hope this helps.  Meanwhile, I think I'll have to downgrade.

**Comment by topfunky** [comment]
I believe I've found the problem. In previous versions, if a directory name was passed, PeepOpen considered that to be the project root directory and didn't try to find a root directory on its own (via .git, Rakefile, Makefile, etc.). That behavior was removed between 0.3.0 and 0.3.1 (in both the app and the TextMate plugin).

I'm reverting it right now and will release a new version. 

I have minimal unit tests but will plan a better suite of integration tests to keep features from disappearing like that in the future.

**Comment by topfunky** [comment]
Version 0.3.2 has been uploaded. Run "Check for Updates" or download from PeepCode.

I was able to reproduce a bug similar to what I see mentioned here, especially if you're working with a project in TextMate that doesn't have a .git, a README, or any other file that would identify the root of the project (but TextMate knows the project root since you opened the directory).

You'll need to re-install the TextMate plugin from PeepOpen preferences (and quit TextMate).

Respond here if you still see the bug mentioned in this ticket.

Before the next major release, I'll work on putting together a more comprehensive test suite to catch these kinds of regressions.

**Comment by granth** [comment]
On 2011-03-25, at 20:56, topfunky wrote:

> Version 0.3.2 has been uploaded. Run "Check for Updates" or download from PeepCode.

Thanks. Fixed it for me. (TextMate, directory open is a git repo, home directory two levels up is a repo.)

**Comment by granth** [comment]
Spoke too soon! Subsequent reloads switched back to my home directory, even after restarting TextMate and PeepOpen.

**Comment by ghost** [comment]
Just installed the update (0.3.2), seems good so far.

**Comment by handcoding** [comment]
Previous versions of Peepopen worked fine for me, but I started seeing this issue since updating to 0.3.2.

In my case, I'm using Git and I do also have a README in the root directory of the each of my projects. I've tried deleting the preferences-plist file and I've also tried reinstalling the TextMate plugin. Any other ideas I should try?

**Comment by topfunky** [comment]
@handcoding Did you quit TextMate and restart? The plugin won't reload with the standard "Reload Bundles" menu item.

**Comment by handcoding** [comment]
@topfunky Yup, I have quit TextMate and restarted. I've also tried PeepOpen's "Install Plugin" without TextMate running. (If there's any debugging data I can send to you, I'd be happy to do so.)

**Comment by thredup** [comment]
Fixed it for me. Thanks!  

PS.  Looking forward to next screencasts :)

**Comment by handcoding** [comment]
@topfunky As 0.3.1 seemed to work okay for me, by any chance could you put up a temporary dropbox link for that?

**Comment by topfunky** [comment]
@handcoding http://dl.dropbox.com/u/1989993/PeepOpen-0.3.1.dmg

But there is a known bug (as mentioned in this thread) in 0.3.1. I'm surprised that it would fix the bug mentioned here, but tell me if it works better than 0.3.2.

**Comment by handcoding** [comment]
@topfunky Thanks for that 0.3.1 link. For what it's worth, I downgraded to that (from 0.3.2), reinstalled the TextMate plugin, and the problem does seem to have gone away for me. 

(If there're any logs or other data that I can send your way, just let me know. It'd be no trouble.)

**Comment by iaj** [comment]
Mh, I'm still having trouble with 0.3.2 - no matter what directory I'm in I always receive the list of my $HOME folder.. .Dunno what's wrong, any chance to share a working 0.3.0 | 0.3.1 link for me please?
