### ISSUE TITLE
PeepOpen crashes when I press cmd+t in Textmate with v0.3.1

### ISSUE THREAD

**Issue by furstenberg** [topfunky/PeepOpen-Issues#201]
Updated to v0.3.1 from v0.3.0 today. After the update as soon as I press cmd+t in Textmate (Version 1.5.10 (1631)) PeepOpen crashes. The Go to File... window is briefly open before it closes. Nothing shown in the window.

I've removed PeepOpen (app, plist and plugin) and installed it again. Same results.
I've tried turning off the git metadata too. No luck.
This happens in folders with .rvmrc and folders without.

Is this only me?

**Comment by furstenberg** [comment]
From the crashlog:

```
Process:         PeepOpen [19404]
Path:            /Applications/PeepOpen.app/Contents/MacOS/PeepOpen
Identifier:      com.topfunky.PeepOpen
Version:         ??? (0.3.1)
Code Type:       X86-64 (Native)
Parent Process:  launchd [8958]

Date/Time:       2011-03-22 14:01:51.351 +0100
OS Version:      Mac OS X 10.6.6 (10J567)
Report Version:  6

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Crashed Thread:  3  Dispatch queue: com.apple.root.default-priority

Application Specific Information:
abort() called
objc[19404]: garbage collection is ON
Thread 3 Crashed:  Dispatch queue: com.apple.root.default-priority
0   libSystem.B.dylib 0x00007fff87476e4e __semwait_signal_nocancel + 10
1   libSystem.B.dylib 0x00007fff87476d50 nanosleep$NOCANCEL + 129
2   libSystem.B.dylib 0x00007fff874d36a2 usleep$NOCANCEL + 57
3   libSystem.B.dylib 0x00007fff874f2cd4 abort + 93
4   libSystem.B.dylib 0x00007fff87472c52 _Unwind_Resume + 66
5   libSystem.B.dylib 0x00007fff87476aab _Unwind_Resume_or_Rethrow + 27
6   libstdc++.6.dylib 0x00007fff8188ab87 __cxa_rethrow + 73
7   PathOperation.rbo 0x000000010378e3a6 MREP_AAF4087A9B294A0C8F241C2A2A0B8762 + 2886
8   com.apple.Foundation 0x00007fff863cbde4 -[__NSOperationInternal start] + 681
9   com.apple.Foundation 0x00007fff864aabeb __doStart2 + 97
10  libSystem.B.dylib    0x00007fff874402c4 _dispatch_call_block_and_release + 15
11  libSystem.B.dylib    0x00007fff8741e831 _dispatch_worker_thread2 + 239
12  libSystem.B.dylib    0x00007fff8741e168 _pthread_wqthread + 353
13  libSystem.B.dylib    0x00007fff8741e005 start_wqthread + 13
```

**Comment by topfunky** [comment]
That's frustrating. Is this on a new MacBook Pro or on an i5 or Core Duo 2 processor?

**Comment by furstenberg** [comment]
Yes very frustrating. :-) It's a early 2008 MacBook Pro (MacBookPro4,1). 

I think I've had every version since it was released. Never had any problem. Until now. And I don't have v0.30 around so I can't try that.

**Comment by furstenberg** [comment]
Think I closed this by a mistake. Oh well.

I upgraded to 10.6.7 since the last comment. I tried again on the same projects as yesterday with the same results.

But saw your links to v0.3.0 and installed that. Works like a charm again. Good to know.

I then updated to v0.3.1 and got the same results as earlier. :-(

So anything you want me to try?

**Comment by furstenberg** [comment]
Tried the following:

Two files, about.html and index.html in a folder called test. Whole path is: ~/dev/test/

Crashes just as before. My console output is:
    TextMate[1359]  OakprojectController (PeepOpen), sending url peepopen:///Users/michael/dev/test/index.html?editor=TextMate to NSWorkspace

**Comment by topfunky** [comment]
That's useful to know that the bug was introduced in 0.3.1. I'll try to reproduce the bug and figure out a solution.

**Comment by furstenberg** [comment]
Upgraded to 0.3.2. Installed plugin again, and it kind of works. If I uncheck "Show metadata with files" it works. If I have it checked, I get a spinning beach ball and peepopen does not respond. I'll do some more testing later and see what I can find.

**Comment by furstenberg** [comment]
0.3.2 works for me now. I do not know why it didn't work the first day, but it does now.

I've tested with "Show metadata with files" on and off on several different projects, both with git repos and not, and it all works. :-)

**Comment by topfunky** [comment]
Sounds great!

**Comment by mgomes** [comment]
It still beach balls for me on 0.3.2 with "Show metadata with files" checked. It happens consistently across various Rails apps that are git-versioned. Turning it off seems to fix the problem.

**Comment by furstenberg** [comment]
Have you tried any of the earlier versions? Or did it appear first in 0.3.2?
