### ISSUE TITLE
no longer opens the files in textmate, opens them in their own window instead

### ISSUE THREAD

**Issue by inspire22** [topfunky/PeepOpen-Issues#203]
This is new with 0.3.1, how do I downgrade to 0.3?

**Comment by inspire22** [comment]
Dangit, still opens files in a new window with 0.3.0, argh!

**Comment by inspire22** [comment]
there was a stray symlink to another copy of the code elsewhere, and that filled up the # files seen, so then it was trying to open files textmate didn't index.

**Comment by topfunky** [comment]
Interesting. Thanks for the sleuthing. I've seen other bug reports about symlinks and need to reproduce those errors.

**Comment by jims** [comment]
I found that if you open your project through the "Open Recent" menu in textmate, files will no longer open in the same window. If you open textmate from the terminal (for a folder i.e. mate . &) files will open in a new tab.
