### ISSUE TITLE
Projects on encrypted volumes

### ISSUE THREAD

**Issue by josh** [topfunky/PeepOpen-Issues#204]
Having an issue after upgrading to `0.3.1`. 

It seems that projects on other Volumes are indexing the entire volume root instead of scoping to the project directory.

I'm using the latest `peepopen.el` and verified that the correct project is being passed along. I can even reproduce the issue from the command line.

```
open peepopen:///Volumes/37signals/basecamp?editor=Emacs
```

`0.3.0` is okay, using that for now.

**Comment by topfunky** [comment]
I'll check this out and try to reproduce the bug.

We did some work to make it handle paths with spaces, but it may be causing this issue.

**Comment by bryanjswift** [comment]
I'm encountering this issue as well using the MacVim plugin. I moved the directory from an encrypted volume to my desktop (~/Desktop) and it works fine. However I have other projects on the same volume that interact with PeepOpen as expected.

**Comment by bryanjswift** [comment]
Interestingly enough, in both projects that failed miserably I had an .rvmrc file in them and I'd only visited the directories via symlinks. Visiting the raw path in terminal and accepting the .rvmrc file seems to have fixed the issue.

**Comment by josh** [comment]
Appears fixed on 0.3.5.
