### ISSUE TITLE
PeepOpen searching a level above my current directory

### ISSUE THREAD

**Issue by philcrissman** [topfunky/PeepOpen-Issues#207]
(Using Textmate.)

Peepopen now seems to be searching starting at a level _above_ my current directory. So, when I'm in:

  ~/Projects/the_project

when I cmd-t, I get files from ALL the different projects in ~/Projects... where, prior to this version, I would just get results from ~/Projects/the_project.

This basically renders it unusable; after it indexes the first few thousand files in ~/Projects, it stops, and nothing in ~/Projects/the_project even shows in the results at all...

As near as I can tell, this just started with the latest version.

**Comment by topfunky** [comment]
I'm addressing this issue over in #200.

**Comment by philcrissman** [comment]
Awesome; I did search, must have missed it.
