### ISSUE TITLE
Disable "Couldn't find a Project" dialog

### ISSUE THREAD

**Issue by greystate** [topfunky/PeepOpen-Issues#209]
The new "Couldn't find a Project" is a major issue when you've just dragged a folder onto TextMate - EVERY time I search for a file, that dialog pops up, forcing me to hit space first to dismiss it before I can search.

I do most of my projects like that - many in Subversion which I haven't found an easy filter to apply in the Advanced Prefs...

**Comment by topfunky** [comment]
I'm addressing a similar issue over in ticket #200.
