### ISSUE TITLE
MacVim: Selected file should open in window or split that called it

### ISSUE THREAD

**Issue by topfunky** [topfunky/PeepOpen-Issues#21]
The selected file sometimes opens in an arbitrary window. If several windows or splits are open, it should open in the one that was active when PeepOpen was originally called.

**Comment by bradly** [comment]
This is happening to me as well in 0.1.9

**Comment by topfunky** [comment]
Could you post the version of MacVim you're using? In MacVim snapshot 52, I'm able to use multiple splits and windows, and it opens in the correct one.

You'll also need to set MacVim's preferences to "Open files in the current window and set the arglist."

**Comment by bradly** [comment]
I did not have open in the current window set. I'll retest tonight.
