### ISSUE TITLE
PeepOpen do not work when directory have @ on name

### ISSUE THREAD

**Issue by sobrinho** [topfunky/PeepOpen-Issues#213]
Hi,

I'm working on a directory named:

<pre>/Users/sobrinho/.rvm/gems/ruby-1.9.2-p180@rails3/gems/activerecord-3.0.5</pre>

And PeepOpen do not work showing files outside root directory.

Cheers

**Comment by sobrinho** [comment]
Oh, I forget. I'm using TextMate and latest version of PeepOpen

**Comment by topfunky** [comment]
Fascinating. I'll check this out. I'm working on several directory-related bugs today.

**Comment by maxim** [comment]
Just had PeepOpen accidentally index my whole $HOME directory because of that (~hundred thousand files). : ) On the plus side — it was mad fast at doing that.

**Comment by topfunky** [comment]
I tried this with the latest 0.3.2 and wasn't able to reproduce the bug (the ticket was originally filed with an earlier version).

A directory like ~/tmp/foo@bar/myapp works as expected.

Reopen this ticket if you're still seeing the unexpected behavior in 0.3.2.

**Comment by sobrinho** [comment]
That's working now!

Thanks
