### ISSUE TITLE
don't work in Textmate

### ISSUE THREAD

**Issue by releu** [topfunky/PeepOpen-Issues#214]
If I open in textmate folder, where folder name includes spaces, cmd+t does not work.

**Comment by releu** [comment]
Textmate v1.5.10 (1631)
PeepOpen v0.3.1

**Comment by topfunky** [comment]
We fixed this in the TextMate plugin included in 0.3.1. 
- Try re-installing the plugin from PeepOpen preferences
- Quit TextMate
- Relaunch TextMate.

If you still see the error, reply and can look into other options.
