### ISSUE TITLE
Peepopen inaccessible after update

### ISSUE THREAD

**Issue by HansCz** [topfunky/PeepOpen-Issues#217]
I just now installed the most recent update of peepopen. It directs me to reinstall the textmate plugin after the update. I updated, but since I have hidden the menu bar Icon I have no way of accessing Peepopen's preferences via the dropdown. There's no menu bar icon to click :) Hence, no textmate plugin update, and it has ceased to function.

Am I missing something painfully obvious?

**Comment by HansCz** [comment]
More succinctly, perhaps: How do I bring the menu bar icon back, or even trash the peepopen prefs to bring it back?

**Comment by topfunky** [comment]
Preferences can also be reached by the sprocket icon on the PeepOpen "Find" window. If you have the old TextMate plugin, you should still be able to pull it up with Command-T.

Or, find a directory you want to open and type this at the command line:

```
open "peepopen:///Users/my-user/path/to/project?editor=TextMate"
```

It will open the PeepOpen window (assuming the app is running) and you can use the sprocket icon to get to Preferences.

I'm thinking about putting the TextMate plugin into Sparkle so it will update automatically when the app does.

**Comment by HansCz** [comment]
the 
    open "peepopen:///...?editor=TextMate"
suggestion worked! Thanks.
