### ISSUE TITLE
Support more Emacs keybindings

### ISSUE THREAD

**Issue by febuiles** [topfunky/PeepOpen-Issues#23]
It would be nice to close the window by pressing C-g instead of having to hit ESC, or being able to scroll down a page by using C-v instead of having to do C-n.

**Comment by topfunky** [comment]
I've implemented C-g to hide the window...it will be in 0.1.9.

Scrolling by pages goes against the idea of what the app is about: filtering via fuzzy search. If there are that many records still visible, you should type more characters or I should make the fuzzy search smarter.

The latest update favors filename searches over paths and should work better than before, with fewer characters (if you search for characters in a filename).
