### ISSUE TITLE
MacVim: Directory has space(s) then cannot toggle PeepOpen

### ISSUE THREAD

**Issue by ngocphamm** [topfunky/PeepOpen-Issues#236]
Hi guys,

I currently have an issue using PeepOpen with MacVim editor. I have browsed through some topics here but cannot find the way out of it. Please help me with this though I am not sure it might come from MacVim or PeepOpen.

The problem is I cannot open PeepOpen when I am currently in a directory which has space(s) in its name, for example "Eclipse Workspace". After changing to this directory (:cd ~/../Eclipse Workspace), PeepOpen just doens't show up when I triggle <leader>-p as usual. If I change to parent directory which doesn't have space(s), for example "Documents", it works well and also shows results from "Eclipse Workspace" directory.

Is it an issue from MacVim "cwd" command or from PeepOpen?

Thanks in advance.

Andy

**Comment by airblade** [comment]
This is due to the way PeepOpen's MacVim plugin escapes the name of the current working directory.  As of v0.3.2, it does this:

```
silent exe "!open 'peepopen://" . shellescape(cwd) . "?editor=MacVim'"
```

Using this instead fixes the problem:

```
silent exe "!open \"peepopen://" . shellescape(cwd) . "?editor=MacVim\""
```

In other words, replace `'` with `\"`.

**Comment by ngocphamm** [comment]
This trick force an error (or warning?) message that says: "Couldn't Find a Project ...."

Please see the screenshot below:
![PeepOpen warning](http://f.cl.ly/items/0A3o3X291W3O281w3X10/Screen%20shot%202011-06-23%20at%201.00.39%20AM.png)

**Comment by airblade** [comment]
That's a different problem.  Your original problem is solved though.

PeepOpen generally expects to be launched within a "project".  It looks like you want to launch it instead in an umbrella directory containing multiple projects.  I think a workaround for you would be to create an empty file in your `Eclipse Workspace` directory, perhaps called `root.txt`, and add `|root\.txt` just before the final `)$` in PeepOpen's Preferences > Advanced > Projet Root Pattern.

**Comment by ngocphamm** [comment]
Thank you, airblade. But it doesn't seem to work within my "project" directory which has `.git` directory although `.git` pattern is in the Project Root pattern setting. Then if the problem consists, the modification makes no sense.

Please see screenshots below:

![PeepOpen settings and directory structure](https://img.skitch.com/20110622-cyw12td7w9k2ebdpepr82jahhp.jpg)

![PeepOpen warning message again](https://img.skitch.com/20110622-rk4wwg9we3e1cw9bme9889jrwc.jpg)

**Comment by airblade** [comment]
I agree with you, that looks wrong.  I don't know how to fix this though; hopefully @topfunky can come to the rescue.

**Comment by ngocphamm** [comment]
I hope so, too. Anyway, thank you for your support, airblade! :-)

**Comment by topfunky** [comment]
The updated plugin with @airblade's suggestion fixes it for the first invocation, then reverts to the non-space version. It's probably something in the app itself that's not respecting whitespace. I'll pursue this further.

**Comment by ngocphamm** [comment]
Thanks @topfunky! Hope this will be fixed soon.

**Comment by ngocphamm** [comment]
Newest PeepOpen release (0.3.4) with @airblade's suggestion seems to fix the problem.
- Change to a directory with space(s), toggle PeepOpen successfully.
- Change to another directory without space, toogle PeepOpen successfully.
- Quit MacVim and PeepOpen, then re-open MacVim, change to a directory with space(s), toogle PeepOpen successfully!

Thanks so much for the fix, @topfunky!
