### ISSUE TITLE
keyboard input lags while search is processing

### ISSUE THREAD

**Issue by bigethan** [topfunky/PeepOpen-Issues#237]
I have a bunch of files scanned by peepopen (12,617), which I know will take a bit of time to search.  I'm ok with that.

But, given my situation,it'd be nice if the search didn't try to re run the search on every keyup.  It'd be much faster if it either waited until I'd stopped typing for a bit, or if it wouldn't search until I hit enter.  The search isn't actually that slow, it's more a matter of running the search ~10 times on a 10 char search that slows the whole process down.

A pref or config (.peepconf?) would be greatly appreciated.

**Comment by topfunky** [comment]
This should be faster in 0.3.4. Give it a shot.

**Comment by bigethan** [comment]
It's certainly faster, but the issue still exists.
