### ISSUE TITLE
Parse TextMate project files for filepaths

### ISSUE THREAD

**Issue by jxpx777** [topfunky/PeepOpen-Issues#238]
I created a TextMate project and it contains files and folders located in a variety of filesystem locations. When working with this project, PeepOpen only offers me the files contained in the directory that holds the .tmproj file itself, which is not correct.

The .tmproj file is just a plist with an array at key "documents" that contains a series of dictionaries describing the files and folders contained in the project. Folders have a name key and sourceDirectory key while individual files have a simple filename key that points to the actual file.

Without this kind of parsing, PeepOpen is much less useful when working with TextMate projects but works really well otherwise.

**Comment by topfunky** [comment]
Unfortunately, supporting .tmproj files is rather complicated and we have chosen to focus on optimization before adding this feature.

This is mentioned in yellow highlight right under the screenshot of PeepOpen: http://peepcode.com/products/peepopen

PeepOpen currently works with projects contained in a single directory, but not with files in separate directories or .tmproj files.
