### ISSUE TITLE
tab from search bar then enter doesn't  work

### ISSUE THREAD

**Issue by rubyredrick** [topfunky/PeepOpen-Issues#24]
I'm using PeepOpen with TextMate

When I enter a search, and hit tab, it selects the first hit in the list, and I can use the up and down arrows to make different selections.

This works just like most similar search tools, like Textmate's standard cmd-T dialog box, or the search bar in Safari.

The difference is that in these you can then hit enter to actually select the highlighted hit. This doesn't work in PeepOpen, instead of opening the file it just 'beeps'

**Comment by topfunky** [comment]
You can use the arrow keys while in the search field, without needing to leave it. Just hit up-arrow or down-arrow.

In the next release (later today), Tab will move the selection downward.
