### ISSUE TITLE
Not detecting .git information on open

### ISSUE THREAD

**Issue by scotthenley** [topfunky/PeepOpen-Issues#240]
0.3.3 has stopped detecting .git information on open. I receive a dialog stating 'Couldn't Find a Project'. This was working in the previous version.

**Comment by topfunky** [comment]
Is this with MacVim? I wasn't able to reproduce it with TextMate or Emacs.

**Comment by topfunky** [comment]
I found a weird issue where an extra trailing single quote was being appended to the path when called from MacVim. I've pushed an 0.3.4 update that fixes it until I can figure out why the plugin is adding it to the path.

You should be good to go now.

**Comment by scotthenley** [comment]
0.3.4 fixed the issue for me in MacVim. Thanks!
