### ISSUE TITLE
Spaces in search string result in no matches

### ISSUE THREAD

**Issue by progressions** [topfunky/PeepOpen-Issues#242]
Until version 0.3.4, I was able to type spaces in the search string and they didn't affect the results being matched.  Something changed with the 0.3.4 release and this is not possible now.

We just tried this with my coworker's copy--he had not updated to 0.3.4:
1. We opened his Rails application in TextMate.
2. Cmd-T to open PeepOpen.
3. Typed "unsub mail" to match the file "app/models/unsubscriber_mailer.rb"
4. That file (and others matching the search string) appeared in the window.

Then he updated to 0.3.4.

He typed "unsub mail".
No files were matched at all, in the same project.

The only difference was the 0.3.4 update.

Unfortunately this makes PeepOpen unusable for me--I don't want to have to be that specific with how much I type every time I'm trying to open a file.

If I type "app/models/unsubscriber_mail" then it still matches the file "app/models/unsubscriber_mailer.rb".

If I type "app models unsubscriber_mail" then it still matches the file.  It still seems to be matching spaces in the search string against "/" characters in the path names.  

But if I type "app models unsub mail" then it matches nothing.

Is this a bug or a deliberate change?

**Comment by bugeats** [comment]
BUMP.  This was the first thing I noticed after updating.  It really screws with my flow.  Thanks @progressions for the detailed description.  It matches my experience exactly.

**Comment by RobertLowe** [comment]
Very annoying. 

http://i.imgur.com/Vf6E6.png
http://i.imgur.com/eKdTA.png

I'm on lion, I'm going to try downgrading from 0.3.4.

---

Edit:

Works as expect in 0.3.2

**Comment by quamen** [comment]
+1 First thing I noticed since upgrading.

**Comment by topfunky** [comment]
Spaces in a search were previously ignored but were changed to represent a slash (based on feedback).

Based on further feedback, it seems that people were treating it as all different kinds of characters. I'll switch it back to the old behavior by default and add a preference to make it represent other characters (hopefully later this week).

**Comment by RobertLowe** [comment]
@topfunky: thanks, for the fuzziest search option

Quick question, is there a repo / HEAD somewhere? Or only what's packaged on peepcode (0.3.2)?

**Comment by topfunky** [comment]
Version 0.3.5 reverts to the previous (expected) behavior. You can also configure the character that whitespace represents (Preferences -> Space Searches For...).

**Comment by topfunky** [comment]
@RobertLowe I've uploaded the new code to the PeepCode website. The project hasn't been updated for XCode 4 yet, and there were some path issues for finding MacRuby. I hope to fix that for a future release.

https://peepcode.com/products/peepopen
