### ISSUE TITLE
MacVim: PeepOpen won't show files start with 'log'

### ISSUE THREAD

**Issue by ngocphamm** [topfunky/PeepOpen-Issues#243]
Hi,

I've found another issue with PeepOpen (or PeepOpen plugin for MacVim) today working with my web project.

I found that PeepOpen can't show files start with `log`, for example, `login.php`, `logo.php`. After browsing through the Preferences, I realise that problem comes from `Directories to ignore` options. There's an option to ignore `log` directories (which is a good point) but there should be a mistake here to ignore these above files as well. Removing `log` option from the `Directories to ignore` patterns helps PeepOpen to show those files.

I am using MacVim 7.3 snapshot 58 with PeepOpen 0.3.4.

Please see screenshots below:

![PeepOpen preferences](https://img.skitch.com/20110708-ds6k2hrpjhk3xatddyhutefsf5.jpg)

![MacVim Current Working Directory](https://img.skitch.com/20110708-dgw6jii76iycucu5c44nxh17ps.jpg)

![Actual Directory Structure](https://img.skitch.com/20110708-qa3sigyd2cg1c4eq9dkbirwsw2.jpg)

![PeepOpen unexpected result](https://img.skitch.com/20110708-cf7my4e3ra1hjrbg8upsmni5xh.jpg)

**Comment by topfunky** [comment]
Good catch. I'll change this in the defaults.

**Comment by ngocphamm** [comment]
Do you mean you will remove the `log` option by default?

**Comment by topfunky** [comment]
Fixed in 0.3.5. It adds '\/' to the end of the regex so only full directories are matched. To get this new behavior, go to Advanced Preferences and add an escaped slash (\/) to the end of the "Directories to Ignore" pattern (or delete your preferences in Library/Preferences/com.topfunky.PeepOpen.plist).
