### ISSUE TITLE
Doesn't find files with underscores when query string contains a space

### ISSUE THREAD

**Issue by jnraine** [topfunky/PeepOpen-Issues#244]
Query string's that contain spaces does not return files that contain underscores.  For example, when searching for the file "user_controller.rb", "usercon.rb" will return results while "user con.rb" will not.

**Comment by topfunky** [comment]
Version 0.3.5 reverts to the previous (expected) behavior. You can also configure the character that whitespace represents (Preferences -> Space Searches For...).

**Comment by jnraine** [comment]
wow, that was quick.  Works great.  Thanks!
