### ISSUE TITLE
Fails to open on BBEdit 9.6.3 under Lion

### ISSUE THREAD

**Issue by alletti** [topfunky/PeepOpen-Issues#247]
Gave me an AppleScript error about not being able to find "item 2" in a URL string.
Fixed by changing line 51 of PeepOpen.applescript to:

``` applescript
set AppleScript's text item delimiters to {"file://"}
```

**Comment by jstr** [comment]
The updated applescript for BBEdit, linked to in https://github.com/topfunky/PeepOpen-EditorSupport/issues/2 fixed this issue for me.

**Comment by alletti** [comment]
Thanks, that should work.
