### ISSUE TITLE
Doesn't open into the focused window when more than one TM instance open

### ISSUE THREAD

**Issue by biot023** [topfunky/PeepOpen-Issues#25]
Hi -- I typically use two TextMate windows, and when using PeepOpen, it always opens into the first window that was opened, not the active one.

**Comment by topfunky** [comment]
In the upcoming 0.2.2, the placement of the window is up to you. I'm currently using it with several TextMate projects open at once and it opens the proper project, even when switching between the two frequently.

**Comment by ljuti** [comment]
I'm using 0.3.2 with TextMate and PeepOpen always opens files into the first window instead of the active one.

If you have implemented the placement of the window, how is it configurable? I couldn't locate a fitting setting in preferences.
