### ISSUE TITLE
Using straight from the Terminal, NOT in current project dir

### ISSUE THREAD

**Issue by constfun** [topfunky/PeepOpen-Issues#254]
I really got this to browse a huge and complex "framework" directory that is NOT part of my project, but I have to refer to it extensively for reference. I do this:

I open MacVim in my project dir:

```
mvim /path/to/my/project
(Within vim leader p works well, as designed, to open files in the project dir.)
```

However, I also do:

```
cd /deep/down/the/rabbit/hole/framework
# And when I need to consult a file in the framework
mvim $(find . -name FileName.ext)
```

PeepOpen would make my life so much easier in that second scenario. How can I use PeepOpen to browse that framework directory which resides outside of my project directory?

**Comment by pnomolos** [comment]
call `open peepopen:///path/to/directory` from the terminal to bring up the window :)

**Comment by constfun** [comment]
You just saved me from several irritable moments a day. Thank you!

```
nmap <silent> <Leader>f :silent !open peepopen:///path/to/framework/directory<CR>
```

Now in vim I can do \p to PeepOpen current project and \f to PeepOpen the framework dir for reference.
