### ISSUE TITLE
File does not open in MacVim

### ISSUE THREAD

**Issue by henrypoydar** [topfunky/PeepOpen-Issues#26]
Unfortunately I can't get a file to open with MacVim from PeepOpen, even if I already have a file open.  I employ lots of plugins, but nothing really different from the typical MacVim user, I'm guessing. Perhaps one of them is causing some interference (NERD-tree, FuzzyFinder?)

Steps to reproduce:
- Open PeepOpen, MacVim selected as Application
- From terminal at project root, open up MacVim via `mvim .`
- NERD Tree view is open, open a file
- Invoke PeepOpen with `<leader>p`
- Select a file, press return

Result:
- PeepOpen window disappears
- MacVim loses focus, nothing happens

Environment:
- PeepOpen 0.1.7
- MacVim snapshot 51
- .vimrc, plugins: http://github.com/hpoydar/vim-config
- OSX 10.6.3, spaces enabled
- zsh

**Comment by topfunky** [comment]
I've also experienced this behavior and agree that it's frustrating. Here are the options I'm considering:
- Instead of the current "vim --remote" for opening files, just do an "open -a MacVim" like the other apps. However, this requires you to change some MacVim preferences to open new files in the same window (instead of a new tab).
- Or, use AppleScript to find the frontmost MacVim instance and open the file with it. Could be slightly slower, though.

I hope to experiment with both and push an update by Monday.

**Comment by henrypoydar** [comment]
I like the first idea, if only for avoiding any lag. (PeepOpen is way faster for me than FuzzyFinder, FYI, and represents for me the top reason to switch) I think changing prefs is ok for MacVim users, most of whom have probably tweaked things a bunch already.  

Great work!

**Comment by airblade** [comment]
Another option is to modify PeepOpen's MacVim plugin to send in addition the current window's identifier (c.f. `:echo v:servername`) to PeepOpen, which in turn sends a `vim --servername lettuce --remote` to MacVim (assuming the window's name was lettuce).

**Comment by raskchanky** [comment]
How does one change the MacVim preferences to open new files in the same window, instead of a new tab?  I've searched through all the docs I can find, but this preference seems to elude me.

Update:  ah, I was using the stable version instead of the latest snapshot.  Thanks!

**Comment by airblade** [comment]
In MacVim's preferences, under the General section, set the "Open files from applications" radio button to "in the current window" and the dropdown to "and set the arglist".

**Comment by takeo** [comment]
also, that option is only available is you're using a snapshot, not the stable version

**Comment by topfunky** [comment]
Fixed in PeepOpen 0.1.9, with the preferences tweak as mentioned. See PeepOpen's Help menu for details.
