### ISSUE TITLE
Option to ignore symlinks?

### ISSUE THREAD

**Issue by jdelStrother** [topfunky/PeepOpen-Issues#261]
Hi,
Would it be possible to have an option to not traverse symlinks?  A few of my projects have large directories symlinked across them, resulting in duplicated files in Peepopen.

**Comment by topfunky** [comment]
Interesting idea. I'm going to close this since a more pressing issue is having a .peepignore file that you can use to list directories that shouldn't be indexed by PeepOpen. This could fulfill the same purpose (but slightly more manually).

**Comment by jdelStrother** [comment]
Fair enough, a .peepignore would work great for me.
