### ISSUE TITLE
Opens in Textmate when launched from MacVim

### ISSUE THREAD

**Issue by hoverbird** [topfunky/PeepOpen-Issues#262]
PeepOpen had been working fine for me in MacVim- not sure what's changed but it now always opens my file in TM, even if TM is not running and it's launched from MacVim.  I've tried reinstalling the MacVim plugin- no luck.

**Comment by topfunky** [comment]
Hey, Patrick! Good catch...I just found a bug where PeepOpen is not saving the selected editor in Preferences properly.

But current PeepOpen plugins should not need that setting...they should pass the current editor as an argument when PeepOpen is activated.

A few debugging tips:
- In your installation of the PeepOpen plugin for MacVim, does it list "editor=MacVim"? Mine is line 29 at ~/.vim/bundle/vim-peepopen/plugin/peepopen.vim (using Tim Pope's pathogen bundling plugin)
- Can you open a file from the command line? Try "open 'peepopen://Users/hoverbird/my-project?editor=MacVim' ". Does that open a file in PeepOpen, then open the resulting file in MacVim?

**Comment by hoverbird** [comment]
I'm using @carlhuda's Janus system- on a lark I tried pulling the latest master and re-running the installation task, which seemed to clear everything up.  Thanks for your help Geoffrey!

**Comment by oleander** [comment]
I'm having the same problem. 

This is the launch method being used.

``` vim
function s:LaunchPeepOpenViaVim()
  silent exe "!open -a PeepOpen " . shellescape(getcwd())
  redraw!
endfunction
```

@topfunky Any ideas why?

I'm using Vim 7.3.260 with MacVim 7.3 build 61. PeepOpen version 0.3.5.

**Comment by topfunky** [comment]
@oleander Use the latest Vim plugin and it should work properly. Run PeepOpen's "Install Plugin" for MacVim from PeepOpen preferences. Or see this code where it uses "peepopen:///" and "?editor=MacVim".

https://github.com/topfunky/PeepOpen-EditorSupport/blob/master/vim-peepopen/plugin/peepopen.vim#L29

Or, a bug related to picking your editor in PeepOpen preferences is being fixed right now.

**Comment by oleander** [comment]
I restarted my computer and the problem was gone.
