### ISSUE TITLE
Doesn't work in Lion

### ISSUE THREAD

**Issue by ghost** [topfunky/PeepOpen-Issues#263]
Just installed using Dmg and doesn't show up in menu bar. Tried several times. Even tried reinstalling.

**Comment by kyktommy** [comment]
i have the same problem
open with terminal:

/Applications/PeepOpen.app/Contents/MacOS/PeepOpen
unknown: [BUG] Segmentation fault
MacRuby version 0.6 (ruby 1.9.0) [universal-darwin10.0, x86_64]

Abort trap: 6

**Comment by tspore** [comment]
I'm not getting a trap, but Its also not showing up in the menu for me. 
$ /Applications/PeepOpen.app/Contents/MacOS/PeepOpen
unknown: warning: already initialized constant KInternetEventClass
unknown: warning: already initialized constant KAEGetURL
unknown: warning: already initialized constant KeyDirectObject

**Comment by topfunky** [comment]
It works in Mavericks, so I'm closing this issue.
