### ISSUE TITLE
Doesn't find files past a certain number of subdirectories

### ISSUE THREAD

**Issue by marktran** [topfunky/PeepOpen-Issues#27]
I have a project that is several directories deep. I've noticed that PeepOpen doesn't find files past 7 levels of directories from the root (/).

example:
/Users/tran/code/projects/kc/webapp/inventory
/Users/tran/code/project/kc/webapp/site_media
/Users/tran/code/projects/kc/webapp/inventory/fixtures/

PeepOpen does not find anything past the inventory or site_media directory. I have a bunch of .py files in the fixtures directory and more subdirectories under site_media that don't show up.

My .git is in /Users/tran/code/projects/kc.

**Comment by topfunky** [comment]
It should recurse, and I have several projects with directories deeper than what you show here.

Try increasing the number of files indexed (PeepOpen Preferences menu). Or, I hope to add a UI for listing directories to ignore, which will give you better control over which directories are indexed.

**Comment by marktran** [comment]
PeepOpen seems to fail to open if I set the maximum number of files > 1000.

Output from Console.app:
Apr 17 17:39:13 machine PeepOpen[21268]: undefined method `map' for nil:NilClass

**Comment by topfunky** [comment]
I found the bug...I'm doing a breadth-first search instead of depth-first. This will be fixed in the next update (probably tomorrow/Tuesday).
