### ISSUE TITLE
Not finding all model files.  Prob a rtfm but I read it. ;)

### ISSUE THREAD

**Issue by ChasManRors** [topfunky/PeepOpen-Issues#274]
Help Geoffrey, Chris... peepopen is not finding all the models.  In my test project Peepopen finds my Post model but not my Task.  
I have tried textmate.el versions, you specified v2 and v3.  But non of them seem to work.  I is a video of what I am doing.  http://www.youtube.com/watch?v=WyC8HVmHJ9k
let me know if you want the source files.

**Comment by ChasManRors** [comment]
I see what the problem is now.

When you change versions of textmate.el the new version is not used until you quit PeepOpen and restart it from the tasks bar.   So you can turn this into a feature request instead of a bug.  If a new version of textmate.el is available it uses that instead of the one it has cached.

**Comment by topfunky** [comment]
Interesting. It's probably Emacs itself that needs to reload the .el files. Glad to hear that it was fixed.
