### ISSUE TITLE
Create file if not found and ability to move files

### ISSUE THREAD

**Issue by mwean** [topfunky/PeepOpen-Issues#275]
I'd love to be able to create a file if it doesn't already exist (with a keyboard shortcut) and move files by maybe tabbing into a new field to set the destination path. I think this would make the app a lot more useful.

**Comment by topfunky** [comment]
That's an interesting feature but is way beyond the functionality PeepOpen was built to provide.

Most text editors can create and move files. Maybe it would be better done once you're back in your text editor?
