### ISSUE TITLE
Command-line interface

### ISSUE THREAD

**Issue by jdelStrother** [topfunky/PeepOpen-Issues#279]
Hi
I wrote a command line tool that interfaces with PeepOpen, called 'peep'.  It just launches the PeepOpen gui when invoked, echoes the selected file to stdout, then exits.

I've been using this so I can use PeepOpen from vim inside the terminal, and found it quite handy.  Is there any interest in something like this being worked up into an official part of PeepOpen?

**Comment by topfunky** [comment]
That sounds awesome! I'd even be glad to pay for it. Can you send the code to boss@topfunky.com or send a link?

**Comment by jdelStrother** [comment]
Cool - email sent :)
