### ISSUE TITLE
Support for Coda 2

### ISSUE THREAD

**Issue by rahoulb** [topfunky/PeepOpen-Issues#281]
I've tried just copying the Coda1 plugin to Coda2 but it doesn't seem to work.

**Comment by apolzon** [comment]
According to the panic folks, you _usually_ just need to open the plugin in their plugin creator and re-save it.  I did this, and thought it was working -- the menu shows up, the shortcut works, it pops open the peepopen window...but when you hit enter on an item, it closes the peepopen window and does nothing. :(

Would be great if someone could look into this -- seems like there hasn't been an update in ages.

**Comment by apolzon** [comment]
Victory! After looking at the custom url scheme documentation, I figured moving the Coda 2.app folder to Coda.app might work...it does!

So:
(sudo) mv /Applications/Coda\ 2.app /Applications/Coda.app

Note -- before I opened this issue, I had tried symlinking Coda.app to Coda\ 2.app -- that will not do the trick.

**Comment by pursual** [comment]
Wasn't able to get it to open by re-saving in plugin creator.
