### ISSUE TITLE
Failure to recognize some folders

### ISSUE THREAD

**Issue by patseng** [topfunky/PeepOpen-Issues#283]
I was using the 'devise' gem for a rails project and it generated a folder devise at the path app/views.  However peepopen thinks that the files located at app/views/devise are located at app/views.  Consequently I am unable to open them

**Comment by topfunky** [comment]
Did you activate PeepOpen (Command-T) and hit Command-R to refresh its file listing? I'm using various subfolders of "app" and wasn't able to reproduce the problem.

**Comment by patseng** [comment]
Thanks so much!  I didn't know about command-R and foolishly thought reopening textmate would refresh the file listings.
