### ISSUE TITLE
Lists files in a directory, although directory in "exclude folder pattern"

### ISSUE THREAD

**Issue by jmuheim** [topfunky/PeepOpen-Issues#285]
I have excluded my folder "gems" from TextMate, but PeepOpen is still showing it.

![](https://img.skitch.com/20121001-x3eujfqb3gf7m23b2tgadnn2ek.png)

This seems to be a bug?!

**Comment by topfunky** [comment]
PeepOpen doesn't currently use TextMate's settings, unfortunately.

Open PeepOpen, Preferences, Advanced and you can add to the regular expression for directories to ignore.

**Comment by topfunky** [comment]
Or, store your gems in a directory that is already ignored, such as "tmp".

**Comment by jmuheim** [comment]
Thanks for this useful info.

Anyway, are you still working on PeepOpen? It seems there are a lot of useful features that are still missing, and for a paid application it would be nice to get regular updates.

**Comment by topfunky** [comment]
We're definitely still using daily. I hope to work on it more after our new developer starts later this month.
