### ISSUE TITLE
Support for Chocolat Text Editor

### ISSUE THREAD

**Issue by nesquena** [topfunky/PeepOpen-Issues#286]
With PeepOpen 0.3.0 supporting a [custom URL scheme](http://peepcode.com/system/uploads/2010/PeepOpen-Help/editors%20-%20custom.html) and being easily extended to work with any editor, I would love for the community to add [editor support](https://github.com/topfunky/PeepOpen-EditorSupport) for the [Chocolat](http://chocolatapp.com/) text editor. I may look into this myself at some point but figured it wouldn't hurt to add this here /cc @fileability

**Comment by atg** [comment]
Done! Look for it in 1.4.1 :)

I lost my peepcode login, so I haven't been able to test it. Fingers crossed.

**Comment by topfunky** [comment]
Cool! Email peepcode@topfunky.com and we're glad to help you out with your login.

**Comment by atg** [comment]
Found it. Voilà!

![](http://chocolatapp.com/snaps/peepshow.png)

**Comment by nesquena** [comment]
@fileability Great stuff! Thanks for adding that in so quickly, look forward to testing it.

**Comment by nesquena** [comment]
Tested and this works exactly as expected. Closing, thanks for adding this.
