### ISSUE TITLE
Does not update with newly created files.

### ISSUE THREAD

**Issue by Stevancw** [topfunky/PeepOpen-Issues#293]
Creating a new file in the terminal and using mvim the application does not list new files. Documents to track set to all.

**Comment by topfunky** [comment]
We've built in a manual refresh. When the PeepOpen window is visible, hit
Command-R to refresh the list of files. You can even do this in the middle
of a search.

On Wednesday, July 10, 2013, Stevan Wing wrote:

> Creating a new file in the terminal and using mvim the application does
> not list new files. Documents to track set to all.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/topfunky/PeepOpen-Issues/issues/293
> .

## 

Geoffrey Grosenbach
boss@topfunky.com
........................
PeepCode Screencasts
http://peepcode.com

**Comment by terite** [comment]
I keep running into this, to the point that re-scanning is something I do automatically after every time I open the peepopen window.

It looks like the [FSEvents API](https://developer.apple.com/library/mac/#documentation/Darwin/Reference/FSEvents_Ref/Reference/reference.html)  introduced in 10.5 would be a perfect fit for this problem.

**Comment by topfunky** [comment]
David -

File system notifications are something we want to try out but we'd rather
err on the side of keeping PeepOpen lightweight and giving you full control.

Did you know that you can refresh in the middle of a search and it will
keep your search (but show new files that match)? That's how we use refresh
here.

On Tuesday, July 16, 2013, David Stensland wrote:

> I keep running into this, to the point that re-scanning is something I do
> automatically after every time I open the peepopen window.
> 
> It looks like the FSEvents APIhttps://developer.apple.com/library/mac/#documentation/Darwin/Reference/FSEvents_Ref/Reference/reference.htmlintroduced in 10.5 would be a perfect fit for this problem.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/topfunky/PeepOpen-Issues/issues/293#issuecomment-21050672
> .

## 

Geoffrey Grosenbach
boss@topfunky.com
........................
PeepCode Screencasts
http://peepcode.com
