### ISSUE TITLE
Should be a taskbar app only

### ISSUE THREAD

**Issue by topfunky** [topfunky/PeepOpen-Issues#3]
The application should not appear in the dock or task switcher, but should be an unobtrusive taskbar app.

We plan to implement this after we commission an icon that looks great in the taskbar.

**Comment by noctivityinc** [comment]
+1

**Comment by jacquescrocker** [comment]
Maybe a menubar app instead?

**Comment by jacquescrocker** [comment]
A quick workaround to remove PeepOpen from your Dock (while still have it run in the background) is to open the Info.plist and add the configs:

```
 <key>LSUIElement</key>
 <string>1</string>
 <key>NSUIElement</key>
 <string>1</string>
```

Here's a screencast on what to do: http://cl.ly/JY3/content

After you restart PeepOpen, it'll still run but no longer be in the Dock!

**Comment by mathie** [comment]
+1

+1 to it not being in the taskbar either. Launchbar has the option to appear in neither the dock nor the task bar, instead allowing you access to its preferences (and other things) from a gear menu on the pop up. That's a good model to emulate IMO.

**Comment by mathie** [comment]
@railsjedi Thanks for the tip, it works a treat. :-)

**Comment by tibra** [comment]
+1

**Comment by caffo** [comment]
+1 

I agree with mathie - no dock or taskbar, but a configuration button in the app UI.

**Comment by h3h** [comment]
Agreed with caffo and mathie—invisible app is best.

**Comment by topfunky** [comment]
Version 0.2.0 has just been released and is a menu bar app.

I hope to add a preference to make it (optionally) even more invisible in a future release, but at least it's out of the app switcher and dock now.

Run "Check for Updates" to get it.
