### ISSUE TITLE
file opening in wrong window

### ISSUE THREAD

**Issue by wayneeseguin** [topfunky/PeepOpen-Issues#32]
The issue I am having is that I typically have several projects open
simultaneously in several separate windows and when I do <leader>-p
and search for then choose a file it opens up in the wrong project
window.

So for example if I have a project open editing RVM and a project editing rvm-site and I <leader>-p
while inside RVM's project window it ends up opening the file I select in rvm-site's window.

**Comment by topfunky** [comment]
This should be fixed in 0.1.9, released last week. Run "Check for Updates" from the "PeepOpen" menu. You'll also need to use a recent snapshot of MacVim (I use 52) and edit the preferences to "Open files in the current window and set the arglist."
