### ISSUE TITLE
Setting 'Maximum Number of Files to Search' greater than 1000 doesn't work

### ISSUE THREAD

**Issue by marktran** [topfunky/PeepOpen-Issues#34]
When I set the "Maximum Number of Files to Search" greater than 1000, PeepOpen doesn't open.

Here's the error message from Console.app:
Apr 21 12:57:43 redacted PeepOpen[87662]: undefined method `map' for nil:NilClass

**Comment by marktran** [comment]
I just tried this again today and now the PeepOpen window appears but it still says "1000 records" in the lower left hand corner.

**Comment by marktran** [comment]
I'm getting the same thing in v0.2.0 except now setting it greater than 500 doesn't work. I'm running "GNU Emacs 23.2.1 (x86_64-apple-darwin, NS apple-appkit-1038.29)."

May 12 12:02:01 redacted PeepOpen[1540]: undefined method `map' for nil:NilClass

**Comment by topfunky** [comment]
Definitely weird. I'll try to reproduce this error.

**Comment by marktran** [comment]
In v0.2.1, if I set the number of "Documents to Track" greater than 1000 and try to "Reload Files" I get the following error: "Try another directory or see the Project Root Pattern preference in the Advanced tab."

**Comment by topfunky** [comment]
In 0.2.4 there is now an "All" option, and the progress bar shows the number of files being loaded. Does this help at all?

**Comment by marktran** [comment]
I haven't seen this error popup since the last couple of updates. Probably safe to close.
