### ISSUE TITLE
opens a new MacVim window for every file opened

### ISSUE THREAD

**Issue by adzap** [topfunky/PeepOpen-Issues#35]
Every file I open is being opened in a new window. This is MacVim Snapshot 52.

**Comment by davidjrice** [comment]
I'm experiencing this as well

**Comment by topfunky** [comment]
Change your MacVim preferences to "Open new files in the same window...and set the arglist." This will fix it.

The steps are also documented in the Help documentation within the app (v0.1.9).

**Comment by adzap** [comment]
thanks that works
