### ISSUE TITLE
Latest Peepopen update has a caching bug

### ISSUE THREAD

**Issue by rese** [topfunky/PeepOpen-Issues#36]
1. Open macvim
2. Invoke peepopen via shortcut
3. Total files are correct
4. Open a file like style.css
5. Invoke shortcut, now only all css files are listed

(This only happens in the latest version, when caching was introduced. In the meantime I've reverted to the earlier version).

**Comment by takeo** [comment]
I've noticed that you have to open a file manually first (using :e or whatever) and then peepopen works properly after that... annoying, but it's in the help file so I guess that's just the way it is.

**Comment by topfunky** [comment]
I think the "one file must be open" issue might be solvable with a better Vim plugin. I'll git it a shot and see if I can make that work better (with Vim's the value of "pwd").

The other caching issue is confusing. I'll try to reproduce it.

**Comment by airblade** [comment]
This probably doesn't help but on the grounds that any information might be useful when debugging: my MacVim & PeepOpen don't have the "one file must be open" constraint.  I launch MacVim for the first time, invoke PeepOpen for the first time, and we're off to the races.

I also don't see the caching bug described above.

I'm using MacVim snapshot 52 and PeepOpen 0.1.9.

**Comment by topfunky** [comment]
The newly released v0.2.0 has a Command-R shortcut (and menu item) for refreshing the file list. It even works if you're in the middle of a search.

It's also a menu bar app and won't show up in the application switcher or dock.

Run "Check for Updates" and try it out.
