### ISSUE TITLE
Bug:  PeepOpen not refreshing file list

### ISSUE THREAD

**Issue by noctivityinc** [topfunky/PeepOpen-Issues#37]
I am running PeepOpen as a UI agent (not sure if that is what is causing the issue) but when I create a new file, such as a migration or whatever, or rename a file I need to RESTART peepopen to get to recognize the file.   Obviously not good.

Thanks.

**Comment by ajwalters** [comment]
Almost created a new bug for this.  This is happening for me in a MacVim Rails project.  Created new partial, tried to find it but couldn't.  After restarting PeepOpen, the file was found

**Comment by kule** [comment]
+1 same here using TextMate

**Comment by wfarr** [comment]
+1 in TextMate as well, though I'm not running PeepOpen in any special way.

**Comment by topfunky** [comment]
The list of files is indeed cached for the duration of the app. The next version will have a menu item to refresh, or possibly detect changes automatically.

Also, the unreleased version in development is a menu bar app, so you won't need to use UI agent.

**Comment by topfunky** [comment]
The newly released v0.2.0 has a Command-R shortcut (and menu item) for refreshing the file list. It even works if you're in the middle of a search.

It's also a menu bar app and won't show up in the application switcher or dock.

Run "Check for Updates" and try it out.
