### ISSUE TITLE
Adding a space should work like it does in textmate

### ISSUE THREAD

**Issue by noctivityinc** [topfunky/PeepOpen-Issues#4]
In Textmate, if you do Cmd+T and type something like "user controller" it will pull up the users_controller.rb file.  But in PeepCode, you need to type "usercontroller," which is very odd.  

Is there a reason for this?  Can you fix it so spaces are basically ignored so it works more naturally?

**Comment by topfunky** [comment]
Searching for "usercontroller" still picks up the correct file with less typing. 

But ignoring spaces (or treating them as an underscore) would be possible. I'll look into it.

Thanks for the feedback!

**Comment by noctivityinc** [comment]
yes and I agree, but the issue is that PeepCode only works ONCE a file has been opened.  There are a number of times, including when I launch TM and open a project, that NOTHING is open, so when I cmd+T I get TM's file finder, which allows me to do "user controller."  Then it switches to PeepCode's finder where I can't enter a space.  

The inconsistency is very odd from an user perspective.

Thanks!

**Comment by topfunky** [comment]
This has now been implemented and will be in an update tomorrow.

**Comment by noctivityinc** [comment]
hi - is this live?  should I update?

**Comment by noctivityinc** [comment]
This ROCKS!!!  1.18 is great.
