### ISSUE TITLE
Matcher can't find test.rb or blueprints.rb in Textmate

### ISSUE THREAD

**Issue by zubin** [topfunky/PeepOpen-Issues#40]
Searching "blue" should match spec/blueprints.rb, but instead if finds really obscure matches. Same with "test" and "testrb" - doesn't find config/environments/test.rb. Tried "conenvtest" and again, obscure matches were found but not the one I was after.

**Comment by topfunky** [comment]
The newest update 0.1.9 prefers filename matches and scores them higher. 

Are you seeing this problem on the latest version, or an older version? The version number is in the "PeepOpen" application menu's "About" screen. Update with "Check for Updates" on the same menu.

**Comment by zubin** [comment]
Am using latest version: 0.1.9. It looks like the spec and config directories are skipped (but not config/initializers).

**Comment by topfunky** [comment]
The upcoming v0.2.1 includes an Advanced preference pane for editing which directories and files to skip. It should fix this problem.
