### ISSUE TITLE
Hide from dock

### ISSUE THREAD

**Issue by cmer** [topfunky/PeepOpen-Issues#41]
You should allow us to hide the app from the dock.

**Comment by marktran** [comment]
This is a duplicate of: http://github.com/topfunky/PeepOpen-Issues/issues#issue/3

**Comment by topfunky** [comment]
Fixed in development and will be released in an update next week. It will be a menu bar app only (with possibly an option to remove that, too).

**Comment by cmer** [comment]
Amen.
