### ISSUE TITLE
Does not track changes in fs, e.g. git co <branch>, within TextMate

### ISSUE THREAD

**Issue by kmayer** [topfunky/PeepOpen-Issues#42]
Create a git repos with two branches, create a file (FILE) in one branch (branch-A) but not the other (branch-B). git checkout branch-A, open textmate (mate `pwd`)

Use Peep-Open to find the FILE, open it.

Now, in a terminal window, "git checkout branch-B"

When click to focus on TextMate, the pane with FILE in it goes away (as it should), now call up Peep-Open and start typing FILE. It is still in the list, even though it is no longer present in the directory.

I discovered this when switching between branches on a rails project, and a controller existed in one branch but not the other.

**Comment by topfunky** [comment]
The app currently caches the file list once (for performance). The next version will have a menu option to refresh the file list, or possibly discover changes automatically.

**Comment by kmayer** [comment]
I think its called fsevent... essentially you can register a callback on a directory so your app can be alerted to changes.

**Comment by topfunky** [comment]
The newly released v0.2.0 has a Command-R shortcut (and menu item) for refreshing the file list. It even works if you're in the middle of a search.

It's also a menu bar app and won't show up in the application switcher or dock.

Run "Check for Updates" and try it out.
