### ISSUE TITLE
Keep last search

### ISSUE THREAD

**Issue by jzting** [topfunky/PeepOpen-Issues#49]
I find myself searching for similarly-named files a lot--it would be nice to keep the last search in the text field so the same results would appear.  Perhaps have the text preselected so the user can quickly overwrite to enter a new search.

**Comment by scottillogical** [comment]
I've always wanted this in textmates' Command+T.  Often times you're not sure what file you are looking for (new code base or whatever) so you need to look at the source of a few similarly named files that might be the one.  Or its your code base, and you just forgot.  

Have the text be preselected means that typing would immediately overwrite and that'd be fine, but for fast switching it would suck.  Ideally fast switching would be a different hotkey, as searching for files is complicated enough.
