### ISSUE TITLE
MacVim opens file in TextMate

### ISSUE THREAD

**Issue by sunny36** [topfunky/PeepOpen-Issues#5]
I have both MacVIM and TextMate plugin installed.

When using MacVIM the file gets opened in TextMate rather than in MacVIM.

**Comment by topfunky** [comment]
The app currently manages a single editor at a time. You'll have to change the preferred editor in PeepOpen's Preferences if you want to switch editors.

I'm looking into the possibility of returning to the app that most recently opened the dialog, but don't have an estimate for when (or if) that could be implemented.

Thanks for the feedback!

**Comment by eventualbuddha** [comment]
I would also like this!

**Comment by powdahound** [comment]
This would be great to have. I switch between TextMate and XCode all the time and would love PeepCode to keep up!

**Comment by topfunky** [comment]
PeepOpen 0.3.0 now supports multiple editors. Run "Check for Updates" and install the new plugins in the Preferences window. You'll be able to use TextMate and MacVim simultaneously.
