### ISSUE TITLE
caching bug with folders

### ISSUE THREAD

**Issue by sinefunc** [topfunky/PeepOpen-Issues#50]
To reproduce:
1. Start macvim
2. open a file in a folder i.e. config/assets.yml
3. now when you invoke peepopen, the list of files are just scoped to the config folder.

**Comment by topfunky** [comment]
I think this is a feature, not a bug.

The PeepOpen plugin for Vim currently uses your value for :pwd when launching. So if you want it to index a directory other than the one printed to the screen when you type :pwd, you'll need to manage that yourself (in Vim). Many other Vim plugins also work with your current value shown by :pwd.

I recommend the vim-rooter plugin, which was written for this very situation. When you open a Ruby file (or a few other types), it looks upward for a .git directory and sets that as the working directory. You can also manually activate it with Leader-cd.

```
http://github.com/airblade/vim-rooter/
```

Or, use Vim's native :cd to navigate to the root of your project, then activate PeepOpen as usual.

I might consider implementing this as part of PeepOpen, but it's currently the job of the individual editor plugins and seems to work best that way.
