### ISSUE TITLE
Pasting into the search field closes the window

### ISSUE THREAD

**Issue by topfunky** [topfunky/PeepOpen-Issues#51]
Reproduce:
- Paste text into the search field
- The window closes

Expected:
- The window should stay open.
- The text should appear in the search field.

**Comment by invalidusrname** [comment]
This is happening to me too. I'm in the habit of copying class names from libraries I'm not used to, so it would be nice if the window didn't close.

**Comment by terrcin** [comment]
happening for me to, for me when I'm pasting in the name of a new migration

**Comment by jnstq** [comment]
Same for my, not able to paste or copy

**Comment by topfunky** [comment]
Fixed in upcoming 0.2.1
