### ISSUE TITLE
Allow configuration of files to ignore

### ISSUE THREAD

**Issue by keithpitty** [topfunky/PeepOpen-Issues#53]
I've tried using PeepOpen on a large Rails project that contains heaps of assets (e.g. swfs) that are ignored by git and I've also set them to be ignored by TextMate. However, since I can't tell PeepOpen to ignore them, it doesn't find some files the search (presumably because they're outside the bounds of the maximum number of documents).

Anyway, it would be nice to have an option to ignore files that are set to be ignored in .gitignore or some other method of constraining PeepOpen to search for files that I'm interested in finding.

**Comment by topfunky** [comment]
Definitely a highly requested feature and high on my list of features to implement soon.

**Comment by topfunky** [comment]
The upcoming v0.2.1 has an Advanced preference pane with a spot for a Regex that filters out unwanted directories and files. A future version will have a nicer Predicate builder.

**Comment by keithpitty** [comment]
Excellent! Looking foward to v0.2.1 being available.
