### ISSUE TITLE
New files aren't found quickly

### ISSUE THREAD

**Issue by mmangino** [topfunky/PeepOpen-Issues#60]
When I create a new file using script/generate, that file isn't found. I'm not sure if that's because I'm using PeepOpen on a number of projects with well over 4000 files. Is there anything I can do to debug this?

**Comment by whatbird** [comment]
additionally > i see the new CMD+R reload feature for refreshing the file list. is this going to happen automatically in an upcoming version?

the file list seems to be sorted by modified time, however peepopen doesn't seem keep updating a file's modified time, as it changes. which makes the sort inaccurate or useless.

**Comment by cmer** [comment]
The 4000 file limit is definitely hurting me too. It makes PeepOpen completely useless for me :(

**Comment by topfunky** [comment]
It's a tradeoff between speed and performance. For most people, speed is a priority.

I hope to implement this in a background thread so files will be updated and refreshed frequently, but I don't have a firm release date for when it will be implemented.

**Comment by topfunky** [comment]
The upcoming v0.2.1 searches in a background thread and shows a progress indicator while searching, which should help this problem.
