### ISSUE TITLE
Re-index files everytime it is triggered?

### ISSUE THREAD

**Issue by fullofcaffeine** [topfunky/PeepOpen-Issues#66]
Whenever you add a new file to the directory tree, peepcode won't index it until you restart the application.

This is really annoying as when you are starting a Rails app, you are adding new files all the time, and they don't automatically appear on peepopen.

I'm not sure what would be the best solution to this issue, maybe reindexing everytime Peepopen is triggered? 

Marcelo.

**Comment by topfunky** [comment]
The newest 0.2.0 has a "Reload Files" menu option (or Command-R) to refresh the file list.

You can even run it with a search in process and it will keep the search active (adding any new files to the list in order).

**Comment by fullofcaffeine** [comment]
Thanks Geoffrey, works smoothly :)
