### ISSUE TITLE
PeepOpen menu is empty in MacVim

### ISSUE THREAD

**Issue by devth** [topfunky/PeepOpen-Issues#69]
This only seems to happen on projects that I've git cloned. Is there something special about cloned git projects that peepopen has trouble with? PeepOpen works on the same project on the machine that it was started on..

Also, if I mvim from another project directory that works, test PO, then go back to my original mvim, cmd+T now shows the files from the other project. If i hit cmd+r it clears out and is blank again.

**Comment by devth** [comment]
This happened on a second project now. I've been working on it at work, but cloned it at home today. Opened mvim, cmd+t and PO just says "Loading" at the bottom left status bar and won't pull up any files.

**Comment by devth** [comment]
Now happening on my work machine. Always seems to occur when I git clone a repo instead of initiating it on my machine. In this case, the project is a basic WordPress install.

Screenshot:
http://dl.dropbox.com/u/113427/peep_open.png

This is killing me to not be able to depend on a learned behavior (cmd+t).

**Comment by devth** [comment]
Any plans to fix? I haven't seen a PO update in a long time.

This happens in about 50% of my projects now. Many of them are rails projects, and one was a wordpress project. Can't figure out what causes this to start happening. When it breaks I have to resort to command-t.vim (which is mapped to ,t). Very disruptive.

**Comment by topfunky** [comment]
We fixed some of the project-finding code in 0.3.0 and 0.3.1. Re-open this ticket if you're still seeing this issue.
