### ISSUE TITLE
"not supported on this type of mac"

### ISSUE THREAD

**Issue by whatbird** [topfunky/PeepOpen-Issues#7]
attempting to open peepopen (0.1.7) gives me a: "not supported on this type of mac" (twice)

intel mac, OS is 10.6.3.

**Comment by djtal** [comment]
I have the same message on an intel core duo mac book.
OS version X.6.2

**Comment by topfunky** [comment]
In that case, a 64 bit CPU may be a requirement (due to MacRuby).

I think the MacRuby developers are working on this, but I can't guarantee when (or if) it will be fixed.

Email boss@topfunky.com and I'm glad to refund your purchase.

**Comment by djtal** [comment]
Oh thanks for the quick response.
No need to refund my purchase. I will try on my 24'' imac later this week. I think it will work on this one.

**Comment by whatbird** [comment]
ah. alrighty-o, thanks again. 

i've got peepcode unlimited, i guess i'll just download something i don't really want to watch and consider us even.... ;)

**Comment by rajiv** [comment]
http://macruby.infoether.com/blog/2009/03/09/macruby-0.4.html says "MacRuby is now fully working in both Intel 32-bit and 64-bit modes." ... have you tried adjusting the target architectures of the PeepOpen target in xcode? the xcode project included with 0.1.7 has that set to "the build machine" which may be 64-bit in your case. can you try setting it to "Standard (32/64-bit Universal)"?

**Comment by george** [comment]
Also interested in a 32/64-bit universal build.

**Comment by christianchristensen** [comment]
me too

**Comment by BryanDonovan** [comment]
Yeah, a 32 bit version would rock.
