### ISSUE TITLE
Where did the preferences go?

### ISSUE THREAD

**Issue by rubyredrick** [topfunky/PeepOpen-Issues#70]
It used to be when I did cmd-T in textmate it would switch to the peep open app. Now it appears to stay in textmate, although it's clearly the peepopen window.

So there seems no way to set preferences/check for updates ...

**Comment by topfunky** [comment]
By popular demand, it's a menubar app now. Look for this small icon:

```
http://peepcode.com/system/uploads/2010/PeepOpen-16x16.png
```

![PeepOpen Icon](http://peepcode.com/system/uploads/2010/PeepOpen-16x16.png)

**Comment by rubyredrick** [comment]
Unfortunately, Textmate has enough menus that it isn't visible.  And it doesn't seem to be repositionable with cmd-drag ;-(

**Comment by topfunky** [comment]
I'll be adding the menu to the PeepOpen window itself in version 0.2.2

**Comment by topfunky** [comment]
Version 0.2.3 has just been released and has an option in Advanced Preferences to hide the menu bar icon.

In all cases, there's a sprocket by the search field that shows the PeepOpen menu.
