### ISSUE TITLE
Can't control which folders are searched in Textmate Project

### ISSUE THREAD

**Issue by rubyredrick** [topfunky/PeepOpen-Issues#71]
For some reason, in one of my projects PeepOpen refuses to look at my spec folder.

How do I control this?  I was trying to figure out how and noticed the 'new' UI which means there's no more menus from peepopen, which is why I just opened http://github.com/topfunky/PeepOpen-Issues/issues/#issue/70

**Comment by topfunky** [comment]
You might need to increase the number of files that are indexed by PeepOpen. Go to the menubar icon, Preferences, and increase the "Maximum Documents to Track" slider.

Or, reply if it still doesn't show up.
