### ISSUE TITLE
[Bug] [v0.2.0] PeepOpen does not find test files in Rails project.

### ISSUE THREAD

**Issue by kgautreaux** [topfunky/PeepOpen-Issues#73]
Expected behavior: Cmd-T followed by typing model_test or model_controller_test finds test files matching this pattern.

Actual behavior: PeepOpen doesn't seem to see test files in a rails project.  Cmd-T followed by typing model_test or model_controller_test doesn't bring up expected files in the find window.

Please see screengrab at: http://dl.dropbox.com/u/5398717/peepopen_test_files_ignored_bug-version-0_2_0.png

Thanks.

**Comment by jacobat** [comment]
Did you crank up the number of "Documents to track"?

**Comment by ericstewart** [comment]
I had this issue too and didn't immediately see tests after cranking up Documents to track, but tests appeared after restarting PeepOpen.

**Comment by kgautreaux** [comment]
This disappeared with v0.2.1 if anyone is wondering.

**Comment by topfunky** [comment]
You can also refresh the list of files with Command-R (after editing the ignore patterns or documents to track in Preferences).
