### ISSUE TITLE
Consider a "Hide Menubar Icon" option

### ISSUE THREAD

**Issue by zdzolton** [topfunky/PeepOpen-Issues#74]
Some Mac users prefer to keep their desktop as minimal as possible. Please provide a preference option to hide the PeepOpen menubar icon.

Thanks for making such a well thought out utility!

**Comment by takeo** [comment]
+1 on this. the amount of time you need to interact with the menu is pretty minimal. maybe some way to get to the same menu from the peepopen window itself? similar to how launchbar has the little gear to get to its main menu so it's accessible even when dock icon is off.

**Comment by bpokosh** [comment]
Look at the app SizeUp for a good example of how this should work.

**Comment by daneharrigan** [comment]
I'd love to have this option! I see its marked as planned, thanks!

**Comment by topfunky** [comment]
Version 0.2.3 has just been released and has an option in Advanced Preferences to hide the menu bar icon.

In all cases, there's a sprocket by the search field that shows the PeepOpen menu.

**Comment by zdzolton** [comment]
Awesome! Thanks again, still loving PeepOpen.
