### ISSUE TITLE
Select All does not work

### ISSUE THREAD

**Issue by jjb** [topfunky/PeepOpen-Issues#75]
I don't know if this is by design -- after typing something in the search field, if one then does command-a to select all the text, the peeopoen window goes away.

With the old command-t in textmate, command-a was a regular part of my workflow, if i wanted to start over and start typing again. so with peepopen, i am constantly accidentally closing the window.

i just read in the tips that escape will do what i want. this is nice and i'm glad i have an option -- but is there any reason for command-a to not work? seems like it would be a typical user's expectation.

thanks for peepopen and thanks for listening!

John

**Comment by topfunky** [comment]
Implemented in the upcoming v0.2.1

**Comment by jjb** [comment]
sweet!
