### ISSUE TITLE
Problem with open .rb files in MacVim

### ISSUE THREAD

**Issue by kossnocorp** [topfunky/PeepOpen-Issues#78]
I just bought the PeepOpen and unfortunately I am having difficulties with open .rb files. I integrate PeepOpen in MacVim and when I open .css, .sass or .yml everything is ok. But when I try open .rb file, MacVim hangs (screencast with demonstration of problem – http://screenr.com/wsK) :(

**Comment by jcf** [comment]
I think this might be an issue with MacVim as I sometimes experience something similar when opening Ruby files within MacVim itself (I'm waiting for it to open a file as I type this).

**Comment by kossnocorp** [comment]
When I manually open .rb files everything is ok. Same for commant-t plugin (http://github.com/wincent/Command-T)

**Comment by kossnocorp** [comment]
After update to 0.2.1 everything is works fine! Thanks! :-)

**Comment by topfunky** [comment]
Glad to hear that it was fixed!
