### ISSUE TITLE
Directory searching in reverse order

### ISSUE THREAD

**Issue by amiel** [topfunky/PeepOpen-Issues#80]
This allows you to specify a filename and then narrow it down by directory. For example, in a rails project with a "broadcasts" resource, I could type ind\broad which would match app/views/(broad)casts/(ind)ex.html.erb.

**Comment by topfunky** [comment]
That's an interesting idea. Right now you can do the same with broad/ind, which seems more intuitive.

**Comment by amiel** [comment]
The concept is that I might search for a file, and then realize that there are too many matches. At which point I can filter through directories without going back to the beginning of the line.
