### ISSUE TITLE
SCM Bug

### ISSUE THREAD

**Issue by cj** [topfunky/PeepOpen-Issues#82]
Hi,

I have SCM enabled http://screencast.com/t/YTczMzBkN but it doesn't show any + or - http://screencast.com/t/MjRiZjNlYTc

Any help getting this working would be great.

Many thanks,

CJ

**Comment by topfunky** [comment]
Thanks for the useful screenshot. I can see that it found your copy of Git at /usr/bin/git, but it is indeed odd that it doesn't show any plusses or minuses.

Ideas:
- Hit Command-R to refresh the list. It should do this automatically, but that would force a refresh
- Run "git diff --numstat" in the project's directory. Does it show any output?

**Comment by topfunky** [comment]
Version 0.2.3 uses a better way to find your copy of Git. If you have a recent version.

If it still doesn't work, feel free to reopen this ticket. Include the version number of Git that you are using.

```
git --version
```
