### ISSUE TITLE
Speed in picking up new files

### ISSUE THREAD

**Issue by DylanFM** [topfunky/PeepOpen-Issues#89]
Hey,
I'm new to this app, so I might be wrong here.. but I ./script/generated a new migration a few minutes ago and it still won't appear in the Peepopen search results. Is there some sort of setting for the time it takes to pick up new files?
Dylan

**Comment by topfunky** [comment]
Hit Command-R in PeepOpen to reload the current project's file list.

I hope to make this automatic in a future version, but haven't implemented a reliable way to do it yet.

You'll also need to reload the files if you change the file or directory ignores in the Advanced tab of Preferences.

**Comment by DylanFM** [comment]
Awesome, thanks mate.

**Comment by JeffCohen** [comment]
The "Reload Files" menu option is always grayed out for me, so I can't reload.  New files are therefore never seen unless I manually quit PeepOpen and restart it.  Any suggestions on how I can diagnose the problem further?  (I also tried re-installing the TM plugin from the PeepOpen preferences but that didn't help.)
