### ISSUE TITLE
Default sort should favor last opened

### ISSUE THREAD

**Issue by topfunky** [topfunky/PeepOpen-Issues#9]
The current starting sort order is last saved files first, but TextMate sorts by last opened.

The initial search list should put previously opened files at the top, then previously saved files if available.

**Comment by takeo** [comment]
Agreed, that's a very nice aspect of textmate's. i think the "last edited" behavior of PeepOpen is great the first time it's invoked, but from then on it should go to "last opened" for easy flipping between files.

**Comment by caged** [comment]
Also agree.  PeepOpen is working out great except for this.  The ability to quickly bounce back and forth between two files I'm actively working on is pretty crucial.  Get on it topfunky!

**Comment by topfunky** [comment]
Fixed in 0.1.9. 

Run the PeepOpen > Check for Update menu to get the new version.

**Comment by caged** [comment]
This is still hit or miss with me in TextMate.  Maybe it's the case where it won't select a previous file if that file wasn't accessed through PeepOpen?
