### ISSUE TITLE
key bindings in MacVim open a new tab instead

### ISSUE THREAD

**Issue by chalmagean** [topfunky/PeepOpen-Issues#90]
<pre>
if has("gui_macvim")
  macmenu &File.New\ Tab key=<nop>
  map <D-t> <Plug>PeepOpen
end
</pre>

this doesn't do anything except open a new tab (I am using FabioAkita's vimfiles http://github.com/akitaonrails/vimfiles)

**Comment by topfunky** [comment]
The default value for Command-T is to open a new tab. This snippet should override it.
- What version of MacVim are you using? I was unable to reproduce the bug with snapshot 52. http://code.google.com/p/macvim/downloads/list
- Do you have the other PeepOpen vim plugin installed elsewhere?
- Did you put the snippet in your ~/.gvimrc or in a different file?

**Comment by chalmagean** [comment]
ok problem solved, I thought .gvimrc is the same as .vimrc so initially I put the snippet in .vimrc which didn't work, but now problem if solved, thank you
