### ISSUE TITLE
peepopen is often ineffective at the most common types of searches

### ISSUE THREAD

**Issue by jjb** [topfunky/PeepOpen-Issues#92]
here's a side by side of PeepOpen and Go To File, for what is for me the most common type of search, beginning to type in a file's full name (or in this case, the file's full name).

![PeepOpen results](http://img.skitch.com/20100618-gnynin6w16qifyb8jky6rbiice.png)

![Go To File results](http://img.skitch.com/20100618-tm9hqxg5kqexhfyq9u8mycw8im.png)

For all of PeepOpen's awesomeness, it fails in this very common case. Or maybe I'm not using PeepOpen for what it was designed for?

Anyway -- thanks for a great tool and for listening!

John

**Comment by topfunky** [comment]
Thanks for the specific example. That's definitely a case where item_spec.rb should appear first (and according to the current algorithm, it should). I'll put this in my unit tests and make it work for the next release.

**Comment by topfunky** [comment]
Fixed in development for the next release (0.2.2).

Explanation: I was giving higher priority to longer matches ("items" in "items_rounting_spec") but now put early matches first (with early matches in filenames scoring even better).

This should also fix some other searches that were a bit wonky.

**Comment by jjb** [comment]
Cool!
