### ISSUE TITLE
Should search on first letters of an underscored word

### ISSUE THREAD

**Issue by topfunky** [topfunky/PeepOpen-Issues#93]
The fuzzy search should consider matches for first letters of underscored words. For example:

```
ppis
```

Should match

```
public_profile_integration_spec.rb
```

As mentioned here:

```
http://railsrx.com/2010/06/17/peepopen-review
```

**Comment by jjb** [comment]
Similar to/same as what I proposed in #83... :)

**Comment by topfunky** [comment]
Duplicate...will address in #83
