### ISSUE TITLE
Should capture keystrokes ASAP upon invoking PeepOpen

### ISSUE THREAD

**Issue by chmurph2** [topfunky/PeepOpen-Issues#94]
I'm using the TextMate plugin.  With TextMate's built in file navigator I would hit ⌘ T and **immediately** start typing my search characters with no issues.  With PeepOpen, it's not opening (or capturing my keystrokes) fast enough and it ends up writing a few characters into the current tab/window instead of PeepOpen.  

It's very frustrating, I have to train myself to wait half a second before typing now.  Hopefully there is something you can do about this.

Oh, and I'm on a relatively new 17" MBP, so it's not a hardware speed issue.

Thanks,
Chris

**Comment by chmurph2** [comment]
I'm using v0.2.1.

**Comment by paulca** [comment]
Hey Geoffrey, +1 on this...

... this catches me out a couple times a day, after 6 weeks using PeepOpen. I love it, and I can deal with crashes every so often for now, but capturing the input immediately on ⌘ T is the frustrating issue at the moment.

**Comment by topfunky** [comment]
If I understand this bug correctly, after a crash, the caches are empty and PeepOpen takes a few seconds to open.

The newest 0.2.2 is compiled instead of using plain Ruby code and may launch slightly faster.

I've done a few things to speed it up, but I think it needs to be much faster on launch. I'll look at some options for the next version, including storing the cached list of files or capturing keystrokes immediately as mentioned.

**Comment by chmurph2** [comment]
Thanks Geoffrey.  I'll use 0.2.2 for a few days before reporting back.  And thanks for looking into it further.

**Comment by paulca** [comment]
This has still been catching me for the last few weeks. I'll give 0.2.2 a go too.

**Comment by chmurph2** [comment]
0.2.2 seems to be capturing my keystrokes with no issues.

**Comment by paulca** [comment]
There's still a slight delay for me, although I've trained myself to wait a second before typing and so I get caught out less.

**Comment by tmeasday** [comment]
+1 -- happens for me regularly on 0.2.3. It's extremely frustrating. I don't think it's a hardware issue. I would be happier if the keystrokes were just thrown away. Having random characters inserted into the currently edited file can be a real nightmare.

**Comment by timdiggins** [comment]
happens for me regularly on 0.2.3. I didn't realize it was actually to do with being after a crash, but it's true, it happens only sporadically, and can't make it happen in normal circumstances, no matter how fast I type.

**Comment by topfunky** [comment]
PeepOpen 0.3.0 uses a background queue and launches much faster. So it should capture keystrokes better than previous versions. Give it a shot with the "Check for Updates" menu item.
