### ISSUE TITLE
MacVim doesn't open the file in a new tab. 

### ISSUE THREAD

**Issue by lucasefe** [topfunky/PeepOpen-Issues#97]
PeepOpen in MacVim opens a selected file in a new window, and not as a new tab in the current window. Is there any way to accomplish this?

**Comment by vesan** [comment]
Change your MacVim settings. Open files from applications: in the current window [with a tab for each file].

**Comment by lucasefe** [comment]
You are the man. Thank you very much. I am a TextMate user switching to Vim... rooki mistake. 

Cheers

**Comment by vesan** [comment]
NP. I'm also a fellow switcher. 2 weeks of full-time Vim use behind me. :-)

**Comment by topfunky** [comment]
Closing...appears to be fixed. Use the latest MacVim snapshot 56 or better for smoother operation with PeepOpen.
